#!/usr/bin/env python3
"""Generate documentation colors from the application's canonical dark tokens."""
import re
from pathlib import Path

DOCS = Path(__file__).resolve().parent


def generated_theme():
    source = (DOCS.parent / "frontend-react/src/theme.css").read_text(encoding="utf-8")
    block = re.search(r':root\[data-theme="dark"\] \{[^}]+\}', source)
    if block is None:
        raise ValueError("Application dark theme token block not found")
    return "/* Generated by docs/build_theme_assets.py; edit frontend-react/src/theme.css. */\n" + block.group(0) + "\n"


if __name__ == "__main__":
    (DOCS / "assets/app-theme.css").write_text(generated_theme(), encoding="utf-8")
