#!/usr/bin/env python3
"""Render decision/evidence without modifying preregistration or measurements."""
import collections,json,pathlib,statistics
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[1]
r=json.loads((ROOT/'docs/auto-resource-estimator-locked-validation.json').read_text());c=r['frozen_contract'];out=[]
def p(s=''):out.append(s)
def f(v):return 'unavailable' if v is None else f'{v:.6g}' if isinstance(v,float) else str(v)
p('# Auto Resource Estimator Locked Validation');p();p(f"**{r['classification']}**. Adaptive-admission DESIGN {'allowed' if r['adaptive_design_allowed'] else 'not allowed'}. Auto remains observation-only. No production behavior changed, no release.");p()
m=r['results']['optimize/cpu_seconds']['metrics'];total=sum(v['observed'] for v in r['completion'].values());planned=sum(v['planned'] for v in r['completion'].values())
p(f"Completed {total}/{planned} planned groups, {len(r['http_requests'])} real HTTP requests and {len(r['predictions'])} prediction records (including secondary recorder controls). Optimize CPU fails: worst raw actual/predicted {m['worst_raw_ratio']:.3f}×, post-margin {m['worst_post_margin_ratio']:.3f}×, post-margin misses {100*m['post_margin_underprediction_rate']:.2f}%; {m['http_failures']} applicable HTTP504 failures. Only Surface, Explain and Azimuth response estimators pass the numerical gates; no useful compute candidate passes.");p()
p(f"Certification is invalid: only {sum(a['sampled_active_seconds']>=c['async_plan']['duration_seconds'] for a in r['sustained_async'])}/72 scenarios reached30s sampled background activity, {len(r['mixed_baseline_gaps'])} mixed comparisons lack matching A/B isolated references, and the reference-completeness guard was added after launch. Frozen models, margins and numeric gates remain unchanged.");p()
p('## Baseline and frozen contract');p();p(f"Clean `{r['baseline']['branch']}`, HEAD `{r['baseline']['head']}`, VERSION `{r['baseline']['version']}`; initial status/diff empty. Calibration source commit `{r['calibration_source_commit']}`. Prior artifacts preserved.");p();p(f"Lock SHA256 `{r['lock_sha256']}`. Domain SHA256 `{r['domain_manifest_sha256']}`. Run-plan SHA256 `{r['run_plan_sha256']}`.");p();p('Prior gates retained: calibration-only margin ≤4; post-margin underprediction ≤5%; worst post-margin shortfall relative to actual ≤10%. Each repeat scores separately, to prevent repeat averaging from hiding safety misses. These gates apply overall and within every geometry band, RF setting, search setting, frequency and resource profile. Failed/timed-out primary requests fail applicable candidates. Missing planned evidence is INSUFFICIENT; overall incomplete or breached validation is D. Negative controls cannot certify.');p()
p('Frozen predictor: `exp(max(-40,min(b0 + Σ bi*(transform(xi)-mean_i)/scale_i,40)))`, retaining the prior numeric clamp. Count/ray/radius/density features use log1p; area uses log(max(x,1e-9)); 28GHz is binary. No hardware, Cell-count, search-policy or contention features exist. Coefficients below include intercept first. Exact means/scales and all formulas are in the JSON and lock.');p()
p('| Estimator | Role | Family / features | Coefficients (intercept first) | Frozen margin | Verdict |');p('| --- | --- | --- | --- | --- | --- |')
for e in c['estimators']:
 p(f"| {e['name']} | {e['role']} | {e['selected_family']}: {', '.join(e['model']['features'])} | {', '.join(format(v,'.17g') for v in e['model']['coefficients'])} | {format(e['calibration_only_margin'],'.17g')} | {r['results'][e['name']]['classification']} |")
p();p('## Domains and settings');p();p(c['domain_selection']['algorithm']);p();p(f"{len(r['domains'])} fresh domains. Bands: {dict(collections.Counter(d['band'] for d in r['domains']))}. Frozen exclusions retain {len(r['domain_exclusions'])} attempted selections (duplicates across band/round targets are intentional). Previous tower IDs and conservative 802m envelopes excluded; new 902m envelopes mutually disjoint. No reselection/replacement occurred. Labelled bands reflect selection targets, not universal density thresholds: exclusions shift surviving ranks. Exact geometry, tower IDs, coordinates and ranks are in the locked manifest.");p()
p('| Domain | Rank | Parts | Vertices | km² | Vertices/km² |');p('| --- | --- | --- | --- | --- | --- |')
for d in r['domains']:
 g=d['stats'];p(f"| {d['id']} | {d['rank']} | {g['footprints']} | {g['vertices']} | {f(g['area_km2'])} | {f(g['vertices_per_km2'])} |")
p();p(f"Unseen RF: {c['rf_settings']}; both 2.6/28GHz,30dBm,120° beam; six Cells for network operations, one for single-cell endpoints, Recommendation supported five. Optimize uses frozen legacy plus `{c['search_settings'][1]}`. No search semantics changed.");p();p(f"Profiles A2CPU/4GiB, B4CPU/8GiB, Ddefault; Auto and policy checked before every batch. {c['matrix']}. Run-order seed {c['run_order']['seed']}; pre-generated shuffled plans hashed before execution.");p()
p('## HTTP, process and sustained-load methods');p();p(str(c['process_reset']));p();p(c['streaming']['transport']+'. '+c['streaming']['receive']+'. '+c['streaming']['measurement']);p();p('Full client wall, client receive and server handler wall are separate observations. Handler wall includes JSON/write; isolated compute wall can be described by handler minus observable encoding/write. Under concurrency the encoding counter is process-wide and not attributed. Bytes are uncompressed response entity bytes drained over TCP, excluding framing. Loopback transfer is not production network performance. Prediction JSONL is exclusive-created, fsynced before request execution and carries request ID/hash plus lock/domain hashes. Report embeds prediction and result logs for chronology audit. Disposable containers retain the image’s port8080 health probe, while this harness uses an ephemeral listener; probe failures therefore do not measure the harness listener. Batch exits and request outcomes are reported separately.');p();p(f"Repeats: {c['repeats']}; no favorable/unfavorable early stopping. Cold evidence means fresh process/index, not cold OS cache. Startup and first RF request separate from warmed later requests.");p();p(str(c['async_plan']));p();p(f"{len(r['sustained_async'])}/72 sustained scenarios recorded. Four scenarios: Optimize, Evaluate, Optimize+Evaluate, two distinct-client Optimizers, all with background activity; sparse/dense, A/B/D, three repeats. Queue/job/active/completed/canceled time series retained as hashed gzip files in `scripts/auto-resource-estimator-validation/evidence/`; JSON links each archive to its original and compressed hashes. Mixed CPU is aggregate process demand and cannot validate individual CPU predictions.")
if r['sustained_async']:
 p();p(f"Observed sampling durations {f(min(a['duration_seconds'] for a in r['sustained_async']))}–{f(max(a['duration_seconds'] for a in r['sustained_async']))}s; active sampling duration {f(min(a['sampled_active_seconds'] for a in r['sustained_async']))}–{f(max(a['sampled_active_seconds'] for a in r['sustained_async']))}s. Full gap/overlap evidence is in JSON; incomplete sustained activity cannot be averaged away. Refill submissions share the unchanged protected-route global slots: two Optimizers can occupy both slots, causing429 refills and exhaustion of the locked64-submission bound. Accepted/cached/denied counts and completed/canceled runs are explicit in JSON. This is not a queue-size or worker-count change.")
p();p('## Estimator errors and classification');p();p('| Estimator | n incl. mixed / primary expected | Raw misses | Worst raw actual/predicted | Post-margin misses | Worst post-margin ratio | Median absolute relative error | Largest raw overestimate | Verdict |');p('| --- | --- | --- | --- | --- | --- | --- | --- | --- |')
for name,v in r['results'].items():
 m=v['metrics']
 if m:p(f"| {name} | {m['n']}/{v['expected']} | {m['raw_underprediction_count']} ({100*m['raw_underprediction_rate']:.2f}%) | {f(m['worst_raw_ratio'])} | {m['post_margin_underprediction_count']} ({100*m['post_margin_underprediction_rate']:.2f}%) | {f(m['worst_post_margin_ratio'])} | {100*m['median_absolute_relative_error']:.2f}% | {100*m['maximum_overestimate']:.2f}% | {v['classification']} |")
 else:p(f"| {name} | 0/{v['expected']} | — | — | — | — | — | — | {v['classification']} |")
p();p('Surface response, Simulate/Evaluate/Interference/Explain/Azimuth response, Optimize CPU/wall/response, Surface CPU/wall, Recommendation CPU/wall, Building Entry wall and negative controls are evaluated separately. No missing estimator invented; RSS, allocations and cgroup observations do not certify memory reservation.');p()
for key,title in [('band','Geometry bands'),('rf_setting','RF setting generalization'),('search_setting','Search setting generalization'),('frequency_ghz','Frequency generalization'),('profile','Hardware transfer')]:
 p('### '+title);p();p('| Estimator | Stratum | n | Worst raw ratio | Post-margin miss rate | Worst post-margin shortfall |');p('| --- | --- | --- | --- | --- | --- |')
 for name,v in r['results'].items():
  for label,m in v['breakdown'][key].items():p(f"| {name} | {label} | {m['n']} | {f(m['worst_raw_ratio'])} | {100*m['post_margin_underprediction_rate']:.2f}% | {100*m['worst_post_margin_shortfall']:.2f}% |")
 p()
p('### Planned mixed-scenario latency and observed overlap');p();p('| Profile | Domain | Scenario / operation | Isolated median s | All-request median / max s | All-request median / max inflation |');p('| --- | --- | --- | --- | --- | --- |')
for m in r['mixed_load']:p(f"| {m['profile']} | {m['domain']} | {m['scenario']} / {m['operation']} | {f(m['isolated_median'])} | {f(m['sustained_median'])} / {f(m['sustained_max'])} | {f(m['median_inflation'])} / {f(m['max_inflation'])} |")
p();p('Mixed statistics above retain every planned interactive request, including requests after background exhaustion; they are not all sustained-load measurements. The JSON separately reports observed-overlap subsets, non-overlap counts and overlap durations. No low-overlap or failed request was dropped from estimator scoring.');p();p('Mixed baseline gaps: '+str(r.get('mixed_baseline_gaps'))+'. These are insufficient matched inflation evidence; no different-setting baseline substituted or extra case added after timing.');p();p('## Memory and preflight observation');p();p('Memory remains observational.50ms sampling misses short transients; lifetime cgroup peak includes startup/prior work. Allocation totals are work, not live reservation. Test/client overhead remains included. Recorder controls and primary HTTP share inputs but have separate process/cache histories, so the following differences are descriptive, not causal estimates of previous recorder inflation. Historical recorder-heavy RSS cannot be retrospectively corrected.');p();p('| Profile | Band / operation | Recorder−HTTP RSS MiB | Recorder−HTTP heap MiB | Recorder−HTTP allocation MiB |');p('| --- | --- | --- | --- | --- |')
for x in r['recorder_comparisons']:
 m=x['measures'];p(f"| {x['profile']} | {x['band']} / {x['operation']} | {m['rss_sampled_max_bytes']['recorder_minus_http']/2**20:.3f} | {m['heap_sampled_max_bytes']['recorder_minus_http']/2**20:.3f} | {m['allocation_bytes']['recorder_minus_http']/2**20:.3f} |")
p();p('Only four matched D-profile recorder comparisons are available. The locked fractional A/B matrix has no matching500m primary cases for those recorder controls. Previous recorder-induced memory inflation cannot be quantified causally from this design.');p()
p();p('Frozen geometry preflight is deterministic and independent of RF results. Domain selection/repeat preflight invoke only index queries, no RF. Primitive tests cover multipart and closed-ring accounting, empty sources and envelope nesting; malformed metadata JSON is rejected and unknown operations yield no estimate. The failure observation found that a nil metadata source returns zero counts: this is an unsafe unknown-to-zero ambiguity in the frozen diagnostic primitive. Primary runs use a successfully loaded, identified real dataset; no unavailable-source estimate is used. Future preflight design must reject unknown sources rather than treating them as empty geometry. The frozen prototype has no query-budget state. Admission remains unimplemented. Bounded query cost is sample evidence only, no hard query complexity guarantee.');p()
for profile,items in r['preflight'].items():
 if items:
  vals=[x['wall_seconds'] for x in items if x['kind']=='footprint-vertices-edges'];alloc=[x['allocation_bytes'] for x in items if x['kind']=='footprint-vertices-edges'];p(f"Profile {profile}: {len(items)} preflight samples; metadata batch-average median {statistics.median(vals)*1e6:.3f}µs/query, worst {max(vals)*1e6:.3f}µs/query, max allocation {max(alloc)/1024:.3f}KiB/query; raw timing retained in JSON.")
p();p('Preflight failure observation: '+str(r.get('preflight_failure_observation')));p();p('## Leakage, completeness and production invariance');p();p(str(r['leakage_audit']));p();p('No validation row influenced coefficients, transforms, selected features, margins, selection, RF/search settings or numeric estimator gates. The matching-reference completeness guard was added to scoring after launch: it implements a requirement from the original task, discovered through plan inspection, but was not explicit in the lock. This is a methodology limitation requiring D; observed numeric PASS values are not certification. All immutable hashes are verified before each batch and at scoring. Only validation harness/report code is added. Planned versus observed rows, exits/OOM state and failures are retained; no silent resume or bad-case exclusion.');p();p('| Batch | Planned | Observed | Complete |');p('| --- | --- | --- | --- |')
for k,v in r['completion'].items():p(f"| {k} | {v['planned']} | {v['observed']} | {v['complete']} |")
p();p('Production invariants:20 attempts/ClientIP/anchored60s; concurrency2 global/1 client; RF deadline60s; Cell cap6; workers1/queue16; Auto observation-only. RF equations, optimizer/search semantics, frontend request shape, scientific fingerprints and persistence untouched. Existing budget/deadline E2Es include frozen scientific hash verification. Cross-dataset generalization remains unvalidated: only real Ankara, synthetic sample pack excluded.');p();p('Eight-Cell implication: fixed Cell count in prior fitting means no calibrated Cell-count coefficient; a future predictor may need Cell count, but this validation cannot certify eight Cells or justify a cap change.');p()
p('Full-body response hashes vary in '+str(len(r['successful_response_hash_stability']['unstable_groups']))+' groups, all Building Entry. That response includes runtime `diagnostics.elapsed_ms`; whole-body hashes do not isolate scientific fields. Other successful groups are stable. Scientific invariance is checked separately by unchanged production source and the existing canonical RF tests/E2E fingerprints.');p()
p('## Checks and freeze decision');p();p(str(r.get('validation',{'status':'final checks pending'})));p();p('No VERSION bump or release. Unreleased records the validation documentation; previous calibration artifacts preserved. Freeze the immutable contract, raw evidence and decision; no refit, tuning, changed margin or admission implementation.');p();p('Limitations:');p()
for s in r['limitations']:p('- '+s)
p();p('Created/changed files: Unreleased changelog entry; validation report Markdown/JSON; validation-only scripts, lock/hash, manifest/hash, plans/hash and compressed queue evidence; generated documentation when built. Full raw measurements/predictions and per-request errors embedded in machine-readable report; disposable runtime logs retained under `/tmp/atom-resource-locked-validation/geometry`.');p();p('**Single recommended next action:** '+r['next_action']);p();p('[Full evidence](./auto-resource-estimator-locked-validation.json) · [Frozen protocol and tooling](../scripts/auto-resource-estimator-validation/README.md)')
(ROOT/'docs/auto-resource-estimator-locked-validation.md').write_text('\n'.join(out)+'\n')
