#!/usr/bin/env python3
"""Prospective design criteria; no policy, HTTP service or RF execution."""
import datetime,hashlib,json,pathlib
HERE=pathlib.Path(__file__).resolve().parent
ROOT=HERE.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def freeze():
 path=HERE/'evaluation-lock.json'
 if path.exists():raise ValueError('criteria already frozen')
 base=json.loads((HERE/'baseline.json').read_text())
 for name,digest in base['production_sha256'].items():assert sha(ROOT/name)==digest
 for name,digest in base['preserved_sha256'].items():assert sha(ROOT/name)==digest
 criteria=['legitimate six-Cell usability','legitimate eight-Cell usability','heavy-root abuse resistance','follow-up abuse resistance','shared-IP/NAT pressure','tab behavior','cancellation behavior','replay resistance','implementation complexity','state complexity','process restart semantics','future multi-instance implications','API compatibility','frontend compatibility','observability/debuggability','backwards compatibility','testability','failure atomicity','denial semantics','migration risk']
 value={'schema_version':1,'frozen_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'study':'design only; no new limiter or RF measurements','source_head':base['head'],'VERSION':base['VERSION'],'baseline_sha256':sha(HERE/'baseline.json'),'source_sha256':base['production_sha256'],'prior_evidence_sha256':{name:d for name,d in base['preserved_sha256'].items() if name.endswith(('.md','.json','.sha256')) and not name.startswith('/tmp/')},'criteria':criteria,'selection_method':'hard constraints first, then explicit minimality/tradeoffs; no composite score','required_legitimate_envelope':{
 'L1':{'guarantee':'fresh retained ClientIP bucket: one normal action; if a root is budget-admitted, reserve its mandatory follow-ups so another action cannot cause a mid-queue budget denial','actions':['Evaluate + N sequential maps','Optimize + N sequential optimized maps','single-Cell Azimuth + sector refresh'], 'scope':'budget guarantee only; concurrency, validation, cancellation, deadline, response failure and finite lease still apply'},
 'L2':{'guarantee':'fresh retained ClientIP bucket: the following bounded normal analysis chains complete without budget429','actions':['Evaluate/maps → Interference','Evaluate/maps → Interference → Re-evaluate/maps','Evaluate/maps → Optimize/maps','Optimize/maps → one uncached explanation']},
 'L3':{'guarantee':'one full evaluation cycle → Optimize/maps in the same window from a fresh retained bucket','transport_calls':{'6C':22,'8C':28},'product_decision':'REQUIRED uninterrupted; the existing comparison/optimization UI is a continuation of analysis, and a successful Optimize response without its required maps is not committed as a completed result. This is a stated design recommendation, not an assertion of a user promise.', 'beyond_scope':'another inspection/analysis after L3, repeated L3, or two simultaneous users each demanding L3 may wait for reset; no indefinite action-chain guarantee'}},
 'hard_constraints':{'unassociated_heavy_root_ceiling_per_retained_IP_window':20,'independent_simulate_ceiling_per_retained_IP_window':20,'ordinary_baseline_sequences':'retain all ≤20 ordinary calls in a fresh bucket without pre-existing reservations; pending accepted obligations can temporarily reduce availability and require bounded cleanup','minimum_required_total_RF_admissions':28,'increment_rule':'allow only the mathematically necessary eight additional RF admissions and only server-verified deterministic follow-ups; no unconditional endpoint exemption','denial':'no RF handler work on budget/authorization denial','concurrency':'unchanged2 global/1 ClientIP; no priorities or exemptions','state':'bounded process-local ephemeral only; no RF bodies/results in authorization records','cancel':'spent attempts never refunded; root cannot mint authorization when it fails or is unadmitted','science':'RF inputs, bodies, equations, search, Pareto, fingerprints and persistence unchanged','deployment':'one current Compose app/process; no distributed infrastructure now'},
 'interpretation':'Maintaining every arbitrary RF-call ceiling at20 while permitting a28-call legitimate chain is impossible. The normative tolerance is an exact+8 execution envelope confined to verified dependencies, with legacy independent ceilings preserved. This is a security/product judgment requiring future validation, not a measured security-equivalence claim.',
 'candidate_families':['P0 current20/60','P1 workflow-derived flat thresholds','P2 static integer route weights','P3 root plus verified follow-up allowances: naive and capped variants','P4 separate root/map buckets','P5 prepaid transport or logical reservations','P6 server aggregation'],
 'simulation':'closed-form/offline journey ledgers and boundary bounds only; no running policy enforcement, tokens, request server or RF engines','timing_evidence':'reuse clean successor B; no new RF qualification','candidate_selection':None}
 path.write_text(json.dumps(value,indent=2,sort_keys=True)+'\n');(HERE/'evaluation-lock.sha256').write_text(sha(path)+'  evaluation-lock.json\n');print('FROZEN',sha(path),value['frozen_at'])
if __name__=='__main__':freeze()
