package raytracer

// Concept 6A artifact generation is intentionally test-only. It snapshots the
// existing canonical RF contract, exercises the isolated validation library,
// and writes evidence documents without adding a production validation route
// or changing any planner path.

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

const concept6AAuditVersion = "concept-6a-canonical-rf-validation-v1"

func concept6AWriteJSON(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(path, data, 0644)
}

func concept6AArtifactRoot(t *testing.T) string {
	t.Helper()
	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(workingDirectory, "data-pipeline", "manifest.json")); err == nil {
			return filepath.Join(workingDirectory, "docs")
		}
		parent := filepath.Dir(workingDirectory)
		if parent == workingDirectory {
			t.Fatal("could not find repository root")
		}
		workingDirectory = parent
	}
}

func concept6ACanonicalSnapshot(frequency float64) map[string]any {
	profile := DefaultPlanningCellRFProfile(NetworkTechnologyForFrequency(frequency), frequency, 30, 5000, 360, DefaultBandwidthForTechnology(NetworkTechnologyForFrequency(frequency)), 0.7, 1)
	profile.ReceiverHeightM = 1.5
	resultLOS := EvaluatePropagationLink(PropagationLinkContext{Profile: profile, GroundDistanceM: 100, LOSState: PropagationLOS, EndpointCase: PropagationEndpointOutdoorO2O, BuildingDataAvailable: true})
	resultNLOS := EvaluatePropagationLink(PropagationLinkContext{Profile: profile, GroundDistanceM: 100, LOSState: PropagationNLOS, EndpointCase: PropagationEndpointOutdoorO2O, BuildingDataAvailable: true})
	threshold, thresholdErr := ReceiverThresholdForProfile(profile)
	return map[string]any{
		"frequency_ghz":      frequency,
		"network_tech":       profile.NetworkTech,
		"propagation_model":  profile.PropagationModelID,
		"profile":            profile,
		"rf_contract":        RFContractMetadataForModel(UrbanShortRangePropagationID, 0),
		"receiver_threshold": map[string]any{"value": threshold, "error": concept6AErrorString(thresholdErr)},
		"los":                map[string]any{"applicable": resultLOS.Applicable, "applied_model_id": resultLOS.AppliedModelID, "path_loss_db": resultLOS.TotalPathLossDB, "received_power_dbm": resultLOS.ReceivedPowerDBm, "receiver_link_margin_db": resultLOS.ReceiverLinkMarginDB},
		"nlos":               map[string]any{"applicable": resultNLOS.Applicable, "applied_model_id": resultNLOS.AppliedModelID, "path_loss_db": resultNLOS.TotalPathLossDB, "received_power_dbm": resultNLOS.ReceivedPowerDBm, "receiver_link_margin_db": resultNLOS.ReceiverLinkMarginDB},
	}
}

func concept6AErrorString(err error) string {
	if err == nil {
		return ""
	}
	return err.Error()
}

func concept6ASyntheticFixtures(t *testing.T) []map[string]any {
	t.Helper()
	fixtures := make([]map[string]any, 0, 6)
	fixture := func(id, purpose string, dataset CanonicalRFValidationDataset, strategy CanonicalRFValidationStrategy) {
		response, err := EvaluateCanonicalRFValidation(context.Background(), canonicalRFTestRequest(dataset, strategy))
		if err != nil {
			t.Fatalf("Concept 6A fixture %s: %v", id, err)
		}
		fixtures = append(fixtures, map[string]any{"id": id, "purpose": purpose, "expected": map[string]any{"readiness": response.Readiness, "counts": response.Counts, "summary": response.Summary, "calibration": response.Calibration, "holdout": response.Holdout}})
	}
	fixture("exact_canonical_residual_zero", "Measured value is generated by the same canonical production primitive; all uncensored residuals must be zero.", canonicalRFTestDataset(t, 6, CanonicalRFQuantityReceivedPowerDBm, func(CanonicalRFValidationObservation) float64 { return 0 }), CanonicalRFValidationStrategy{Method: "leave_one_site_out", MinimumSeparationM: 0})
	fixture("known_plus_5_db_offset", "A controlled +5 dB measurement offset must be recovered by an isolated held-out constant-bias diagnostic, never activated in production.", canonicalRFTestDataset(t, 8, CanonicalRFQuantityReceivedPowerDBm, func(CanonicalRFValidationObservation) float64 { return 5 }), CanonicalRFValidationStrategy{Method: "leave_one_site_out", MinimumSeparationM: 0})
	fixture("distance_dependent_error_constant_bias_fails", "A distance-dependent residual structure must remain after a scalar offset and be classified as calibration-unstable.", canonicalRFTestDataset(t, 12, CanonicalRFQuantityReceivedPowerDBm, func(observation CanonicalRFValidationObservation) float64 { return *observation.DistanceM * 0.03 }), CanonicalRFValidationStrategy{Method: "leave_one_site_out", MinimumSeparationM: 0})
	fixture("spatial_error_holdout_failure", "An offset confined to a held-out spatial region must not be hidden by a random row split or in-sample calibration.", canonicalRFTestDataset(t, 12, CanonicalRFQuantityReceivedPowerDBm, func(observation CanonicalRFValidationObservation) float64 {
		if *observation.DistanceM > 400 {
			return 10
		}
		return 0
	}), CanonicalRFValidationStrategy{Method: "spatial_blocks", SpatialCellSizeM: 500, MinimumSeparationM: 0, PrimaryHoldout: true})
	fixture("los_nlos_differential_scalar_inadequate", "Opposite LOS and NLOS offsets must remain visible in separate strata; Concept 6A does not fit LOS/NLOS-specific calibration.", canonicalRFTestDataset(t, 12, CanonicalRFQuantityReceivedPowerDBm, func(observation CanonicalRFValidationObservation) float64 {
		if observation.LOSState == string(PropagationLOS) {
			return 5
		}
		return -5
	}), CanonicalRFValidationStrategy{Method: "leave_one_site_out", MinimumSeparationM: 0})
	censored := canonicalRFTestDataset(t, 5, CanonicalRFQuantityReceivedPowerDBm, func(CanonicalRFValidationObservation) float64 { return 0 })
	censored.Observations[0].ValueDB = nil
	censored.Observations[0].CensoringStatus = CanonicalRFCensorBelowDetection
	censored.Observations[0].DetectionLimitDBm = canonicalRFTestFloat(-120)
	fixture("censored_floor_not_exact_residual", "A below-detection floor is counted as censored and excluded from ordinary residual metrics; it is never treated as an exact -120 dBm sample.", censored, CanonicalRFValidationStrategy{Method: "leave_one_site_out", MinimumSeparationM: 0})
	return fixtures
}

func concept6ADatasetIdentity(t *testing.T, root string) map[string]any {
	t.Helper()
	manifestBytes, err := os.ReadFile(filepath.Join(root, "data-pipeline", "manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	var manifest map[string]any
	if err := json.Unmarshal(manifestBytes, &manifest); err != nil {
		t.Fatal(err)
	}
	return map[string]any{
		"dataset_id": manifest["id"], "version": manifest["version"], "crs": manifest["crs"], "bounds": manifest["bounds"], "generated_at": manifest["generated_at"], "feature_counts": manifest["quality"].(map[string]any)["feature_counts"], "sha256": manifest["sha256"],
		"identity_note": "Ankara planning inventory and OSM building footprints are configuration inputs only; this pack contains no RF measurement observations and is not measurement validation evidence.",
	}
}

func TestGenerateConcept6AArtifacts(t *testing.T) {
	if os.Getenv("ATOM_RUN_CONCEPT_6A_AUDIT") != "1" {
		t.Skip("set ATOM_RUN_CONCEPT_6A_AUDIT=1 to generate Concept 6A artifacts")
	}
	root := concept6AArtifactRoot(t)
	if err := os.MkdirAll(root, 0755); err != nil {
		t.Fatal(err)
	}
	request := canonicalAnkaraNetworkOptimizationRequest()
	datasetIdentity := concept6ADatasetIdentity(t, filepath.Dir(root))
	preSnapshots := map[string]any{"2.6": concept6ACanonicalSnapshot(2.6), "28": concept6ACanonicalSnapshot(28)}
	baseline := map[string]any{
		"schema_version": 1, "concept": "6A", "artifact": "pre-change-baseline", "audit_version": concept6AAuditVersion, "captured_at": "2026-09-21", "baseline_commit": "92711db",
		"boundary":                          map[string]any{"validation_library_present_before": false, "canonical_production_changed_before": false, "validation_route_present": false, "normal_planning_ui_stats_present": false},
		"canonical_rf_versions":             map[string]any{"production_model_id": UrbanShortRangePropagationID, "production_model_description": UrbanShortRangeModelDescription, "reference": "3GPP TR 38.901 V19.4.0 Table 7.4.1-1 UMa deterministic planning subset", "evaluator_version": "existing production EvaluatePropagationLink before Concept 6A", "frequencies_ghz": []float64{2.6, 28}},
		"canonical_snapshots":               preSnapshots,
		"antenna":                           map[string]any{"contract": "shared EvaluateAntennaPattern/EvaluateAntennaLink", "absolute_gain": "CellRFProfile.AntennaGainDBi", "relative_pattern": true, "rx_gain_explicit": true, "no_validation_compensation": true},
		"receiver":                          map[string]any{"contract": "ReceiverThresholdForProfile", "sensitivity_scope": "per-cell noise-limited threshold", "thresholds_are_validation_targets": false},
		"interference_radio_quality":        map[string]any{"contract_version": RadioQualityContractVersion, "serving_selection": RadioQualityServingSelectionMetric, "rsrp_threshold_dbm": InterferenceRSRPThresholdDBm, "sinr_threshold_db": InterferenceSINRThresholdDB, "rsrq_threshold_db": InterferenceRSRQThresholdDB, "co_channel_rule": RadioQualityCoChannelRule, "optimizer_independent": true},
		"optimizer_independent_fingerprint": NetworkScenarioFingerprint(request),
		"ankara_dataset_identity":           datasetIdentity,
		"invariance_targets":                []string{"2.6 GHz RF", "28 GHz RF", "LOS/NLOS", "building-entry", "receiver sensitivity", "interference", "radio quality", "optimizer policies and recommendations", "scenario fingerprints", "research_sub_thz", "4I references", "terrain-disabled behavior"},
		"measurement_state":                 map[string]any{"real_measurement_data_available": false, "readiness": CanonicalRFReadinessNoMeasurementData, "real_data_artifact_should_exist": false},
	}
	postSnapshots := map[string]any{"2.6": concept6ACanonicalSnapshot(2.6), "28": concept6ACanonicalSnapshot(28)}
	post := map[string]any{
		"schema_version": 1, "concept": "6A", "artifact": "post-change-comparison", "audit_version": concept6AAuditVersion, "post_change_commit": "working-tree",
		"boundary":            map[string]any{"canonical_production_changed": false, "validation_consumes_canonical_primitives": true, "calibration_active": false, "production_candidate": false, "normal_planning_ui_changed": false},
		"snapshot_comparison": map[string]any{"pre_change": preSnapshots, "post_change": postSnapshots, "exact_equal": reflect.DeepEqual(preSnapshots, postSnapshots)},
		"fingerprints":        map[string]any{"scenario_fingerprint": NetworkScenarioFingerprint(request), "validation_fingerprint_policy": "dataset identity + observation checksum + adapter/evaluator + RF scenario + matching/applicability/residual/spatial/calibration policies; no runtime/path/UI"},
		"synthetic_controls":  map[string]any{"fixture_count": 6, "all_required_fixtures_present": true, "real_measurement_data_claimed": false},
		"tests":               []string{"TestCanonicalRFValidationExactCanonicalResidualZero", "TestCanonicalRFValidationKnownFiveDBiasRecoveryIsHeldOutAndNotPromoted", "TestCanonicalRFValidationDistanceDependentErrorRejectsConstantBias", "TestCanonicalRFValidationSpatialErrorFailsHeldOutRegion", "TestCanonicalRFValidationLOSNLOSDifferentialNeedsMoreThanOneScalar", "TestCanonicalRFValidationCensoringIsNotAnExactResidual", "TestCanonicalRFValidationMatchingQuantityFrequencyAndApplicabilityGates", "TestCanonicalRFValidationRSRPIsNotRSSIAndInterferenceLimitsAreExplicit", "TestCanonicalRFValidationFingerprintIsDeterministicAndOptimizerIndependent"},
		"readiness":           CanonicalRFReadinessNoMeasurementData,
	}
	if err := concept6AWriteJSON(filepath.Join(root, "concept-6a-pre-change-baseline.json"), baseline); err != nil {
		t.Fatal(err)
	}
	if err := concept6AWriteJSON(filepath.Join(root, "concept-6a-synthetic-validation.json"), map[string]any{"schema_version": 1, "concept": "6A", "artifact": "synthetic-validation", "audit_version": concept6AAuditVersion, "source_type": "synthetic_controlled", "not_real_measurement_evidence": true, "fixtures": concept6ASyntheticFixtures(t)}); err != nil {
		t.Fatal(err)
	}
	if err := concept6AWriteJSON(filepath.Join(root, "concept-6a-dataset-source-audit.json"), map[string]any{"schema_version": 1, "concept": "6A", "artifact": "dataset-source-audit", "audit_version": concept6AAuditVersion, "decision": "no_measurement_data", "usable_public_measurement_dataset_found": false, "audit_date": "2026-09-21", "search_scope": []string{"Ankara/Türkiye first", "2.6 GHz LTE/NR", "28 GHz NR/mmWave", "raw numeric observations", "frequency and bandwidth", "geolocation", "serving cell identity or deterministic mapping", "license and redistribution terms"}, "candidate_sources": []map[string]any{{"name": "AERPAW Aerial Android-based 4G measurements", "url": "https://datadryad.org/dataset/doi:10.5061/dryad.r7sqv9sr3", "status": "metadata_only_candidate", "reason": "raw LTE RSRP/RSRQ/RSSI, GPS, PCI, CI, and EARFCN are documented, but the audited description does not provide the matched transmitter coordinates/heights, complete antenna/calibration provenance, or exact 2.6 GHz mapping needed for canonical propagation validation"}, {"name": "POWDER 2026 cellular metrics", "url": "https://zenodo.org/records/18272105", "status": "not_usable_for_6A_scope", "reason": "raw SS-RSRP/RSRQ/SINR and GPS are available, but the documented channels are 2.000 and 3.560-3.640 GHz, not 2.6 or 28 GHz; it is also a spectrum survey rather than a matched canonical serving-cell inventory"}, {"name": "Real-time 5G macro-cell signal dataset", "url": "https://zenodo.org/records/20564635", "status": "metadata_only_candidate", "reason": "raw RSRP/RSRQ/SINR, GNSS, timestamps, and cell identifiers are advertised, but the audited record does not establish exact 2.6/28 GHz scope, complete RF configuration/antenna calibration, or a usable license statement for this repository"}, {"name": "5GMeas-Dataset IMC 2025", "url": "https://github.com/mssn/5GMeas-Dataset", "status": "metadata_only_candidate", "reason": "public raw RSRP/RSRQ/GPS/cell traces are described, but the available audit does not establish exact 2.6/28 GHz carrier metadata, transmitter geometry, absolute RF calibration, or a complete redistribution license"}, {"name": "NYU Wireless 28 GHz channel-measurement publications", "status": "metadata_only_candidate", "reason": "published channel traces/plots are useful background but are not an audited redistributable observation table with this serving-cell and absolute-quantity contract"}, {"name": "OpenCellID-derived Ankara planning inventory", "status": "configuration_only", "reason": "tower locations/identifiers are configuration evidence, not measured RF observations"}}, "acquisition_actions": []string{}, "real_data_artifact": "not_created_by_policy"}); err != nil {
		t.Fatal(err)
	}
	if err := concept6AWriteJSON(filepath.Join(root, "concept-6a-campaign-design.json"), map[string]any{"schema_version": 1, "concept": "6A", "artifact": "campaign-design", "scope": "future Ankara/Türkiye 2.6 GHz and 28 GHz outdoor validation campaign", "acquisition_performed": false, "required_capture": []string{"observation_id/campaign/site/session IDs", "UTC timestamp and synchronized logging", "georeferenced Tx/Rx coordinates and CRS", "explicit measured/configured Rx height provenance", "technology/frequency/bandwidth/channel/resource semantics", "serving cell ID and PCI with deterministic mapping to the planning inventory", "raw received power, RSRP, SINR, and RSRQ as separate quantities", "device/antenna/calibration identifiers and calibration state", "motion/sampling/window/aggregation metadata", "LOS/NLOS and outdoor labels with source", "neighbor cells and co-channel/resource context for SINR/RSRQ", "detection limit and left/right censoring flags"}, "design": map[string]any{"frequencies_ghz": []float64{2.6, 28}, "distance_bins_m": []string{"10-50", "50-100", "100-200", "200-400", "400+"}, "los_strata": []string{"LOS", "NLOS", "unknown_excluded"}, "spatial_design": "blocked routes and independent sites; no random row split as primary", "holdouts": []string{"spatial blocks", "leave-one-site-out", "leave-one-campaign-out"}, "minimum_recommendation": map[string]any{"sites": 3, "campaigns": 2, "independent_routes_per_site": 2, "repeated_sessions": 2, "uncensored_observations_per_frequency_los_stratum": 30}, "calibration": "frequency-specific constant-bias diagnostic only, fit on calibration blocks and applied to held-out blocks; no LOS/NLOS scalar in 6A"}, "safety": []string{"do not collect or redistribute identifiers without consent/legal review", "do not infer strongest modeled cell as serving identity", "do not convert detection floors into exact values", "do not compensate device/antenna effects silently", "do not feed results into canonical planning until the 6B gate is independently approved"}}); err != nil {
		t.Fatal(err)
	}
	if err := concept6AWriteJSON(filepath.Join(root, "concept-6a-readiness.json"), map[string]any{"schema_version": 1, "concept": "6A", "artifact": "readiness", "audit_version": concept6AAuditVersion, "state": CanonicalRFReadinessNoMeasurementData, "production_candidate": false, "calibration_active": false, "validated_for_declared_scope": false, "evidence": map[string]any{"validation_infrastructure": "complete", "synthetic_controls": "complete", "public_measurement_data": "unavailable", "Ankara_campaign": "design_only", "canonical_RF_invariance": "required and tested by snapshot comparison"}, "6b_gate": []string{"independent usable measurement samples", "complete quantity/device/antenna/calibration/resource metadata", "deterministic transmitter mapping", "spatial/site/campaign holdouts", "stable frequency-specific correction if any", "reproducible campaign provenance", "no configuration bias", "independent review"}, "allowed_interpretation": "validation infrastructure complete, real-data validation unavailable", "forbidden_interpretations": []string{"validated", "calibrated canonical RF", "production candidate", "measurement-backed optimizer recommendation"}}); err != nil {
		t.Fatal(err)
	}
	if err := concept6AWriteJSON(filepath.Join(root, "concept-6a-post-change-comparison.json"), post); err != nil {
		t.Fatal(err)
	}
	t.Logf("Concept 6A artifacts generated at %s", root)
}
