// Code generated by scripts/generate_policy.py; DO NOT EDIT.

package raytracer

const (
	DefaultStaticSimulationRays        = 60
	DefaultNetworkOptimizationRays     = 72
	DefaultRadiusMeters                = 400
	DefaultFrequencyGHz                = 28
	DefaultTxPowerDBm                  = 30
	DefaultBeamWidthDeg                = 120
	DefaultCalibrationOffsetDB         = 0
	DefaultInterferenceBandwidthLTE    = 20.0
	DefaultInterferenceBandwidthNR     = 100.0
	DefaultInterferenceLoadFactor      = 0.7
	DefaultInterferenceReuseFactor     = 1
	DefaultInterferenceNoiseFigure     = 7
	DefaultInterferenceSpacingM        = 40
	DefaultRecommendationResults       = 5
	LTEFrequencyMaxGHz                 = 10
	NRFrequencyMaxGHz                  = 100
	MaxTowerIDBytes                    = 128
	MinLongitude                       = -180
	MaxLongitude                       = 180
	MinLatitude                        = -90
	MaxLatitude                        = 90
	MinSimulationRays                  = 8
	MaxSimulationRays                  = 720
	MinRadiusMeters                    = 25
	MaxRadiusMeters                    = 5000
	MaxFrequencyGHz                    = 300
	MinTxPowerDBm                      = 0
	MaxTxPowerDBm                      = 60
	MinBeamWidthDeg                    = 10
	MaxBeamWidthDeg                    = 360
	MinCalibrationOffsetDB             = -40
	MaxCalibrationOffsetDB             = 40
	MinNetworkTowers                   = 2
	MaxNetworkTowers                   = 6
	MaxRecommendationTowers            = 5
	MinMeasurementTowers               = 1
	MaxMeasurementTowers               = 6
	MinRecommendationResults           = 1
	MaxRecommendationResults           = 10
	MinInterferenceLoadFactorExclusive = 0
	MaxInterferenceLoadFactor          = 1
	MinNoiseFigureDB                   = 0
	MaxNoiseFigureDB                   = 20
	MinSampleSpacingM                  = 20
	MaxSampleSpacingM                  = 200
	RFProfileSchemaVersion             = 1
	DefaultAntennaGainDBi              = 25
	DefaultSystemLossDB                = 0
	DefaultAntennaHeightM              = 25
	DefaultMechanicalDowntiltDeg       = 0
	DefaultElectricalDowntiltDeg       = 0
	DefaultOrientationDeg              = 0
	DefaultReceiverHeightM             = 1.5
	DefaultReceiverSensitivityDBm      = -115
	MaxRFProfileTextBytes              = 64
	MinBandwidthMHz                    = 0.1
	MaxBandwidthMHz                    = 2000
	MinAntennaGainDBi                  = -20
	MaxAntennaGainDBi                  = 80
	MinSystemLossDB                    = 0
	MaxSystemLossDB                    = 100
	MinAntennaHeightM                  = 0.5
	MaxAntennaHeightM                  = 300
	MinDowntiltDeg                     = -30
	MaxDowntiltDeg                     = 90
	MaxRFProfileReuseFactor            = 12
	MinPCI                             = 0
	MaxLTEPCI                          = 503
	MaxNRPCI                           = 1007
	MinReceiverHeightM                 = 0.1
	MaxReceiverHeightM                 = 100
	MinReceiverSensitivityDBm          = -180
	MaxReceiverSensitivityDBm          = -20
)

func NetworkTechnologyForFrequency(frequencyGHz float64) string {
	switch {
	case frequencyGHz < LTEFrequencyMaxGHz:
		return "4g"
	case frequencyGHz < NRFrequencyMaxGHz:
		return "5g"
	default:
		return "6g"
	}
}

func DefaultFrequencyForTechnology(networkTech string) float64 {
	switch networkTech {
	case "4g":
		return 2.6
	case "5g":
		return 28
	default:
		return 140
	}
}

func DefaultBandForTechnology(networkTech string) string {
	switch networkTech {
	case "4g":
		return "LTE Band 7"
	case "5g":
		return "NR n257"
	default:
		return "Sub-THz research"
	}
}

func DefaultDuplexModeForTechnology(networkTech string) string {
	if networkTech == "4g" {
		return "fdd"
	}
	return "tdd"
}

func DefaultBandwidthForTechnology(networkTech string) float64 {
	switch networkTech {
	case "4g":
		return 20.0
	case "5g":
		return 100.0
	default:
		return 1000.0
	}
}

func IsAnalysisTechnology(networkTech string) bool {
	return networkTech == "4g" || networkTech == "5g"
}

func FrequencyMatchesTechnology(networkTech string, frequencyGHz float64) bool {
	return frequencyGHz > 0 && NetworkTechnologyForFrequency(frequencyGHz) == networkTech
}
