import { describe, expect, it } from "vitest";
import { createReportDefinition, validateReportDefinition } from "./report.js";
import { resolveReportSource } from "./reportSource.js";
import { captureOptimizationRun, captureSimulationRun } from "./runCapture.js";
import { createScenarioRevision } from "./scenario.js";
import { buildHistoricalPlanningReport, renderMarkdownReport } from "../utils/reportExport.js";

const REVISION = createScenarioRevision({
  scenario_revision_id: "revision-1",
  scenario_id: "scenario-1",
  planning_mode: "network",
  selected_cell_ids: ["cell-1", "cell-2"],
  enabled_cell_ids: ["cell-1", "cell-2"],
  rf_affecting_settings: { frequencyGHz: 28, radiusMeters: 400, txPowerDbm: 30 },
  optimizer_configuration: { objectives: [{ id: "demand", weight: 100 }], constraints: {} },
  canonical_input_snapshot: {
    settings: { frequencyGHz: 28, radiusMeters: 400, txPowerDbm: 30 },
    planningMode: "network",
    selectedNetworkTowerIds: ["cell-1", "cell-2"],
    inventory: [
      { id: "cell-1", cellId: "cell-1", coordinates: [32.85, 39.92], azimuth: 30, rfProfile: { frequencyGHz: 28 } },
      { id: "cell-2", cellId: "cell-2", coordinates: [32.86, 39.93], azimuth: 210, rfProfile: { frequencyGHz: 28 } },
    ],
  },
  resolved_fingerprints: { scenario_fingerprint: "scenario-fingerprint-1" },
});

const SCENARIO = {
  id: "scenario-1",
  name: "Historic network",
  domain: {
    scenario_id: "scenario-1",
    current_revision_id: "revision-1",
    revisions: [REVISION],
  },
};

describe("Concept 7D report source boundary", () => {
  it("validates a ReportDefinition as mutable metadata, not generated bytes", () => {
    const definition = createReportDefinition({
      report_id: "report-1",
      project_id: "project-1",
      scenario_id: "scenario-1",
      scenario_revision_id: "revision-1",
      run_ids: ["run-1"],
      title: "Historic report",
      sections: ["executive_summary"],
    });
    expect(validateReportDefinition(definition)).toEqual([]);
    expect(definition).not.toHaveProperty("content_hash");
    expect(validateReportDefinition(createReportDefinition({ source_kind: "live_compatibility" }))).toEqual([]);
  });

  it("rejects a Run from another ScenarioRevision instead of silently recomputing", () => {
    expect(() => resolveReportSource({
      project: { id: "project-1" },
      scenario: SCENARIO,
      scenarioRevision: REVISION,
      runs: [{ run_id: "run-other", project_id: "project-1", scenario_id: "scenario-1", scenario_revision_id: "revision-other" }],
    })).toThrow(/ScenarioRevision/);
  });

  it("rejects a historical Run that has no exact revision identity", () => {
    expect(() => resolveReportSource({
      project: { id: "project-1" },
      scenario: SCENARIO,
      scenarioRevision: REVISION,
      runs: [{ run_id: "run-unbound", project_id: "project-1", scenario_id: "scenario-1" }],
    })).toThrow(/exact ScenarioRevision/);
  });

  it("builds a historical simulation report from compact Run evidence and labels unavailable detail", () => {
    const run = captureSimulationRun({
      context: { run_id: "simulation-run-1", project_id: "project-1", scenario_id: "scenario-1", scenario_revision_id: "revision-1", scenario_fingerprint: "scenario-fingerprint-1" },
      result: {
        simulation: { stats: { avg_rx_dbm: -88, max_range_m: 400, min_range_m: 50, blocked_pct: 12 }, geojson: { features: [{ private: "map" }] } },
        coverage_gaps: { stats: { gap_buildings: 3 }, geojson: { features: [{ private: "gap" }] } },
      },
    });
    const report = buildHistoricalPlanningReport({
      appMeta: { model_version: "rf-model-1", dataset: { id: "dataset-1", version: "2026.09" } },
      project: { id: "project-1", name: "Historic project" },
      scenario: { ...SCENARIO, plan: REVISION.canonical_input_snapshot },
      scenarioRevision: REVISION,
      runs: [run],
    });
    const markdown = renderMarkdownReport(report);

    expect(report.domainBinding.scenario_revision_id).toBe("revision-1");
    expect(report.domainBinding.run_ids).toEqual(["simulation-run-1"]);
    expect(markdown).toContain("simulation-run-1");
    expect(markdown).toContain("Detailed signal surface and ray geometry were not retained");
    expect(markdown).not.toContain("private");
    expect(markdown).not.toContain("data-report-section=\"planning-map\"");
  });

  it("preserves optimization baseline, Pareto, recommendation, selected solution, and priorities", () => {
    const capturedRun = captureOptimizationRun({
      context: { run_id: "optimization-run-1", project_id: "project-1", scenario_id: "scenario-1", scenario_revision_id: "revision-1", scenario_fingerprint: "scenario-fingerprint-1" },
      response: {
        optimization_run_id: "optimizer-compute-1",
        baseline: { id: "baseline", stats: { score: 42 }, towers: [{ id: "cell-1", optimal_azimuth: 30 }] },
        pareto_frontier: [
          { id: "solution-1", score: 88, stats: { score: 88 }, towers: [{ id: "cell-1", optimal_azimuth: 55 }] },
          { id: "solution-2", score: 80, stats: { score: 80 }, towers: [{ id: "cell-1", optimal_azimuth: 80 }] },
        ],
        optimization: {
          recommended_solution_id: "solution-1",
          priorities: { demand: 70, coverage: 30 },
          objective_status: { demand: { available: true } },
          constraints: { min_coverage_score: 1 },
        },
      },
    });
    const run = {
      ...capturedRun,
      details: {
        ...capturedRun.details,
        effective_priorities: { demand: 70, coverage: 30 },
        selected_solution_id: "solution-2",
        search_policy: { strategy: "bounded" },
      },
    };
    const report = buildHistoricalPlanningReport({
      project: { id: "project-1", name: "Historic project" },
      scenario: { ...SCENARIO, plan: REVISION.canonical_input_snapshot },
      scenarioRevision: REVISION,
      runs: [run],
    });
    const markdown = renderMarkdownReport(report);

    expect(report.selectedSolutionId).toBe("solution-2");
    expect(report.networkOptimization.baseline.stats.score).toBe(42);
    expect(report.networkOptimization.pareto_frontier).toHaveLength(2);
    expect(report.networkOptimization.optimization.recommended_solution_id).toBe("solution-1");
    expect(report.networkOptimization.optimization.configured_priorities).toEqual({ demand: 70, coverage: 30 });
    expect(markdown).toContain("Selected solution");
    expect(markdown).toContain("solution-2");
    expect(markdown).toContain("Public Pareto solutions");
    expect(markdown).toContain("Full optimizer evaluation ledger was not retained");
  });
});
