// Code generated by scripts/generate_policy.py; DO NOT EDIT.

package main

const policyMaxTowerIDBytes = 128

var allowedCoreLabScenarios = map[string]struct{}{
	"normal":              {},
	"registration_storm":  {},
	"udm_outage":          {},
	"ausf_auth_failure":   {},
	"pcf_policy_degraded": {},
	"upf_degraded":        {},
	"xn_degraded":         {},
	"xn_unavailable":      {},
}

func isAllowedCoreLabScenario(scenario string) bool {
	_, ok := allowedCoreLabScenarios[scenario]
	return ok
}
