#!/usr/bin/env python3
"""Render numeric findings from the final ledger; never synthesize production limits."""
import json,pathlib,statistics
ROOT=pathlib.Path(__file__).resolve().parents[2];D=json.loads((ROOT/'docs/rf-resource-admission-measurements.json').read_text());R=D['rows'];lines=[]
def text(s=''):lines.append(s)
def table(headers,rows):
 text('| '+' | '.join(headers)+' |');text('| '+' | '.join(['---']*len(headers))+' |')
 for row in rows:text('| '+' | '.join(map(str,row))+' |')
 text()
def get(label,f=2.6,n=6,env='native-host'):return next(r for r in R if r['label']==label and r['frequency_ghz']==f and r['n']==n and r['environment']==env)
def fmt(x):return f'{x:.3f}'
def mb(x):return f'{x/2**20:.2f}'
def statuses(r):return ','.join(str(x['status']) for x in r['responses'])
text('## Measured environment and high-water marks');text()
text('The clean native default pass replaced an initial pass that overlapped the Docker image build; both initial ledgers remain in the JSON, explicitly excluded from comparison ratios. One clean observation per route/case is not a latency distribution. RSS/heap are whole-process samples, not exclusively charged request memory.');text()
table(['Environment','CPU / physical or VM memory','Toolchain / scheduler','Storage / quotas'],[['Native macOS arm64','Apple M4; 10 logical CPUs; 24 GiB physical','Go 1.27.1; GOMAXPROCS 10','APFS workspace; environment snapshot includes free/inactive/compressed pages and memory-pressure indicator'],['Normal Docker Linux arm64','OrbStack VM; 10 logical CPUs; 12,600,156,160 bytes VM memory','Go 1.26.6 build; instrumented runtime GOMAXPROCS 10','Overlay filesystem; cpu.max=max 100000; memory.max=max; no Compose quotas'],['Instrumented container test','Same image/dataset/runtime quotas','Cross-compiled Go 1.26.6; non-root host UID for writable test artifacts','Test binary only; normal production HTTP server measured separately']])
S=D['observed_single_request_high_water'];table(['Native single-request dimension','Observed high-water','Case / result'],[[k,f"{v['value']:,}",f"{v['label']} ({v.get('frequency_ghz','')} GHz; HTTP {v.get('status','')})"] for k,v in S.items() if isinstance(v,dict) and 'value' in v and k!='logical_workflow_bytes'])
table(['Geometry counter','Observed single-request high-water','Case'],[[k,f"{v['value']:,}",v['label']] for k,v in S['geometry'].items()])
all6=[r for r in R if r['n']==6 and r['environment']=='native-host'];p=max(all6,key=lambda r:r['rss_sampled_max_bytes']);q=max(all6,key=lambda r:r['heap_sampled_max_bytes']);c=max(all6,key=lambda r:r['equivalent_cores'])
text(f"Across complete native scenarios (including workflows), sampled RSS reached {mb(p['rss_sampled_max_bytes'])} MiB in {p['label']}; heap reached {mb(q['heap_sampled_max_bytes'])} MiB in {q['label']}. Maximum observed average equivalent cores was {c['equivalent_cores']:.3f} in {c['label']}, against ten available logical CPUs. These averages are not instantaneous peaks or a certified spare-core budget. The largest single-request CPU measurement includes a timeout; the largest completed single-request CPU is {S['completed_cpu_seconds']['value']:.3f} CPU seconds. Worst interactive deadline overshoot was {max(r['wall_seconds']-60 for r in all6 if len(r['responses'])==1 and not r.get('async_jobs',0)):.3f} seconds in this finite sample; cooperative cancellation does not prove universal zero overshoot.");text()
text('## Default and high supported route measurements');text()
text('Native canonical fixture: 120 rays, 400 m, 30 dBm, 120° beam; six selected network cells where applicable, 20/100 MHz at 2.6/28 GHz. Recommendation baseline uses two cells and a small polygon; measurement baseline has one observation; experiments have four azimuth runs. Surface endpoint baseline uses the prior canonical 10 m fixture; the true omitted 25 m surface default is measured separately in the sensitivity ledger. Diagnostic reference baselines remain their applicable 140 GHz contract fixtures, not fictitious 2.6/28 GHz versions.');text()
endpoints=['simulate','evaluate-network','optimize-network','interference','explain-network-cell','optimize-azimuth','building-entry-analysis','coverage-surface','recommend-sites','measurements/evaluate','processes/batch-experiment/execution']
table(['Route','GHz','Wall s','CPU s','RSS MiB','Heap MiB','Response MiB','JSON writer s'],[[ep,f,fmt((r:=get('/api/'+ep,f))['wall_seconds']),fmt(r['cpu_seconds']),mb(r['rss_sampled_max_bytes']),mb(r['heap_sampled_max_bytes']),mb(r['response_bytes']),fmt(r['json_serialization_seconds'])] for ep in endpoints for f in [2.6,28]])
text('High settings: 125 rays / 5,000 m / 60 dBm / 360°; alternate map 720 rays / 850 m / 60 dBm / 360°; surface 1,575 m / 10 m grid (99,856 cells); recommendation five baseline cells, up to ten results, full Ankara polygon; measurements 5,000 observations with high effective profiles; optimizer archive budget reaches the validated 64/100,000/5,000/64 settings. Timeout responses are error bodies, not successful payload-size bounds.');text()
highs=['high-simulate','high-rays-radius','high-evaluate','high-optimize','high-interference','high-azimuth','high-building','high-surface','high-recommend','high-measurements','max-search-budget','high-explanation']
table(['High case','GHz','HTTP','Wall s','CPU s','Spatial matches','RSS MiB','Heap MiB','Response MiB','JSON writer s'],[[label,f,(r:=get(label,f))['responses'][0]['status'],fmt(r['wall_seconds']),fmt(r['cpu_seconds']),f"{r['work']['spatial_candidates']:,}",mb(r['rss_sampled_max_bytes']),mb(r['heap_sampled_max_bytes']),mb(r['response_bytes']),fmt(r['json_serialization_seconds'])] for label in highs for f in [2.6,28]])
table(['High/default comparison','GHz','Wall ×','CPU ×','Spatial matches ×','RSS delta MiB','Heap delta MiB','Response ×'],[[r['label'],r['frequency_ghz'],f"{r['wall_ratio']:.2f}",f"{r['cpu_ratio']:.2f}",f"{r['geometry_ratios']['spatial_candidates']:.2f}" if r['geometry_ratios']['spatial_candidates'] is not None else 'n/a',mb(r['rss_delta_bytes']),mb(r['heap_delta_bytes']),f"{r['response_ratio']:.4f}"] for r in D['default_high_comparisons']])
text('## Parameter sensitivity and dominant drivers');text()
labels=['rays-8','rays-60','rays-120','rays-360','rays-720','radius-1000','radius-2500','radius-5000','cells-2','cells-4','cells-6','surface-25','surface-10','interference-spacing-200','interference-spacing-40','interference-spacing-20','measurements-1','measurements-100','measurements-1000','measurements-5000','experiment-1','experiment-4','experiment-16','experiment-64']
table(['Sweep at 2.6 GHz (28 GHz in ledger)','Wall s','CPU s','Spatial matches','Allocation MiB','Response MiB'],[[label,fmt((r:=get(label))['wall_seconds']),fmt(r['cpu_seconds']),f"{r['work']['spatial_candidates']:,}",mb(r['allocation_bytes']),mb(r['response_bytes'])] for label in labels])
text('Ray count, effective radius and footprint/vertex density dominate geometry. Model choice changes polygon/path work even at equal rays. Beam/power/frequency/receiver profile alter range termination and serialized map properties. Cell count multiplies contributions; search policy and unique-evaluation budget change reuse and discovery demand. High interference radius multiplies sample-by-cell path work even though sampling is capped. Surface resolution drives grid work and bytes; building-entry selection can scan the full dataset; recommendation candidate-potential scans precede its RF evaluation cap. Observation and experiment-run counts scale independent loops. Cumulative allocations can far exceed live heap: the worst observed single-request allocation was approximately 172.6 GiB in a 60-second request, indicating GC pressure rather than 172.6 GiB of resident memory.');text()
text('## Concurrent clients, deadlines, and async overlap');text()
labels=['opt-opt','opt-eval','opt-interference','eval-eval','recommend-opt','heavy-map-map','same-IP','three-IP','cancel-high-optimize','cancel-high-evaluate','high-opt-opt','largest-map-pair']
table(['Native combination','GHz','Statuses','Wall s','Aggregate CPU s','Equivalent cores','RSS MiB','Heap MiB','Goroutines','Bytes'],[[label,f,statuses(r:=get(label,f)),fmt(r['wall_seconds']),fmt(r['cpu_seconds']),fmt(r['equivalent_cores']),mb(r['rss_sampled_max_bytes']),mb(r['heap_sampled_max_bytes']),r['goroutines_sampled_max'],f"{r['response_bytes']:,}"] for label in labels for f in [2.6,28]])
for f in [2.6,28]:
 solo=get('/api/optimize-network',f);pair=get('opt-opt',f);same=get('same-IP',f);third=get('three-IP',f)
 text(f"At {f} GHz, two default optimizers inflated maximum per-request wall time by {max(x['wall_seconds'] for x in pair['responses'])/solo['wall_seconds']:.2f}× against the clean solo sample. Same-IP admission executed one and rejected one (both charged, remaining 18); geometry matches were {same['work']['spatial_candidates']:,}, versus {pair['work']['spatial_candidates']:,} for two executed jobs. Three distinct clients executed two and rejected one; its geometry matches equal the two-job case ({third['work']['spatial_candidates']:,}). Cancellation at 100 ms returned after {max(get('cancel-high-optimize',f)['wall_seconds'],get('cancel-high-evaluate',f)['wall_seconds'])-.1:.4f} s of additional wall time, produced zero body bytes, and released slots. Recorder status 200 for canceled/no-body cases is not successful RF output.")
text()
labels=['async-alone-16','async-evaluate','async-optimize','async-two-interactive','heavy-async-plus-two-interactive','configured-four-workers-plus-two','high-experiment-64']
table(['Background scenario','GHz','Wall s (all work)','Aggregate CPU s','Interactive request walls s','RSS MiB','Heap MiB','Sampled async active / HTTP slots'],[[label,f,fmt((r:=get(label,f))['wall_seconds']),fmt(r['cpu_seconds']),'/'.join(fmt(x['wall_seconds']) for x in r['responses']) or 'none',mb(r['rss_sampled_max_bytes']),mb(r['heap_sampled_max_bytes']),str(r.get('async_running_sampled_max','not sampled in initial harness'))+' / '+str(r.get('interactive_slots_sampled_max','not sampled in initial harness'))] for label in labels for f in [2.6,28]])
for f in [2.6,28]:
 r=get('high-experiment-64',f);text(f"At {f} GHz the completed high 64-run job used {r['cpu_seconds']:.3f} aggregate CPU seconds and {r['wall_seconds']:.3f} wall seconds, averaging {r['cpu_seconds']/64:.3f} CPU seconds and {r['wall_seconds']/64:.3f} wall seconds/run for that matrix. These averages include submission/manager sampling and vary with azimuth; they are not uniform per-run maxima.")
q=D['async_queue_measurement'];text(f"Queue audit: {q['accepted']} submissions accepted (one running, {q['queue_depth_at_overflow']} waiting), next submission rejected 429 with remaining {q['remaining'][-1]}; no HTTP slot remained occupied. Canceling jobs drained queued work and the actual worker in {q['cancel_release_seconds']:.6f} s; {q['queued_runs_canceled']} queued runs were prevented. The four-worker row is a gated alternate configuration; default remains one.");text()
text('## Six-cell workflows and test-only eight-cell delta');text()
flows=['A-evaluate','B-evaluate-interference','C-evaluate-interference-reevaluate','D-optimize-map-review','E-optimize-explanation-inspect']
table(['Workflow','Cells','GHz','Attempts','Wall s','CPU s','Spatial matches','RSS MiB','Heap MiB','Bytes'],[[label,n,f,len((r:=get(label,f,n))['responses']),fmt(r['wall_seconds']),fmt(r['cpu_seconds']),f"{r['work']['spatial_candidates']:,}",mb(r['rss_sampled_max_bytes']),mb(r['heap_sampled_max_bytes']),f"{r['response_bytes']:,}"] for label in flows for n in [6,8] for f in [2.6,28]])
table(['6 → 8 default comparison','GHz','CPU change','Wall change','Spatial-match change','Byte change'],[[label,f,*[f"{(get(label,f,8)[key]/get(label,f,6)[key]-1)*100:.1f}%" for key in ['cpu_seconds','wall_seconds']],f"{(get(label,f,8)['work']['spatial_candidates']/get(label,f,6)['work']['spatial_candidates']-1)*100:.1f}%",f"{(get(label,f,8)['response_bytes']/get(label,f,6)['response_bytes']-1)*100:.1f}%"] for label in ['A-evaluate','D-optimize-map-review','C-evaluate-interference-reevaluate'] for f in [2.6,28]])
for label in ['high-evaluate-map-bundle','high-repeat-bundle']:
 for f in [2.6,28]:
  r=get(label,f);text(f"Supported six-cell {label}, {f} GHz: {len(r['responses'])} sequential attempts, {r['cpu_seconds']:.3f} CPU s, {r['wall_seconds']:.3f} wall s, {r['work']['spatial_candidates']:,} spatial matches, {r['response_bytes']:,} bytes, sampled RSS {mb(r['rss_sampled_max_bytes'])} MiB / heap {mb(r['heap_sampled_max_bytes'])} MiB. All requests completed. Memory includes retained recorder copies across the whole workflow, not just one streamed server response.")
text()
text('## Domain, dataset and predictor evidence');text()
table(['Domain / dataset control','GHz','Wall s','CPU s','Spatial matches','Response bytes'],[[label,f,fmt((r:=get(label,f))['wall_seconds']),fmt(r['cpu_seconds']),r['work']['spatial_candidates'],r['response_bytes']] for label in ['domain-canonical','domain-central','domain-peripheral','controlled-synthetic'] for f in [2.6,28]])
text('The peripheral fixture has zero local Ankara footprints and is a sparse-domain lower control. The synthetic dataset contains one controlled footprint (four vertices); its costs are not production-equivalent. Pre-handler R-tree square envelopes found canonical 772 footprints/3,206 vertices, central 614/3,665, peripheral zero. Lookup cost is recorded separately; it is not included in RF timings. More vertices with fewer buildings illustrates why counts alone are incomplete. At 28 GHz, the empty domain produced more response bytes than the canonical dense domain despite less geometry work.');text()
inventory=D['domain_prehandler_inventory']['rows'];text(f"The finite pre-handler inventory lookup sample reached {max(r['lookup_wall_seconds'] for r in inventory):.6f} wall seconds and {max(r['lookup_cpu_seconds'] for r in inventory):.6f} process CPU seconds (different lookups). Counts include complete footprint vertices intersecting each conservative square envelope; they are metadata, not actual RF interaction counts. Even estimation requires its own bounded resource allowance.");text()
table(['Exploratory predictor','Cases','Underestimates','Worst actual / predicted','Worst predicted / actual','Certified?'],[[r['model'],r['cases'],r['underestimated_cases'],f"{r['maximum_underestimation_factor']:.2f}×",f"{r['maximum_overestimation_factor']:.2f}×",'No'] for r in D['predictor_error']])
text('These errors reject the tested estimators as conservative admission rules. Geometry estimates use pre-handler domain footprints with a canonical ray/radius coefficient; byte estimates use canonical bytes/requested-segment budget. Neither proves a schema/geometry upper bound. CPU/geometry/byte estimates require separate calibration and held-out tests; no production reserve or scalar weight is selected.');text()
text('## Container, bandwidth and browser measurements');text()
table(['Normal HTTP image','GHz','Case index','HTTP','Wall s','Cgroup CPU s','Server RSS MiB','Received body bytes'],[[r['endpoint'],r['frequency_ghz'],r['workload_index'],r['status'],fmt(r['wall_seconds']),fmt(r['cpu_seconds']),mb(r['rss_sampled_max_bytes']),r['received_response_bytes']] for r in D['container_measurements']['rows']])
text('Normal container cgroup CPU includes local helper probes and wget; wall includes docker exec and transfer. HTTP 504 error bodies are not captured by wget, so received zero bytes is not a server response-size claim. Separate instrumented container rows supply Go heap, goroutines and geometry with the same Go 1.26.6 toolchain and unmodified quota settings. Geometry matches agree with native defaults for the measured routes; timers and working set differ.');text()
table(['Instrumented Linux workload','GHz','CPU s','Wall s','RSS MiB','Heap MiB','GOMAXPROCS'],[[r['label'],r['frequency_ghz'],fmt(r['cpu_seconds']),fmt(r['wall_seconds']),mb(r['rss_sampled_max_bytes']),mb(r['heap_sampled_max_bytes']),10] for r in R if r['environment']=='instrumented-container'])
targets=[get('high-rays-radius'),get('A-evaluate'),get('C-evaluate-interference-reevaluate'),get('high-evaluate-map-bundle'),get('high-repeat-bundle')]
table(['Payload/workflow (2.6 GHz)','Actual bytes','10 Mbit/s modeled s','50 Mbit/s modeled s','100 Mbit/s modeled s','1 Gbit/s modeled s'],[[r['label'],f"{r['response_bytes']:,}",*[f"{r['response_bytes']*8/(m*1e6):.2f}" for m in [10,50,100,1000]]] for r in targets])
table(['Visible desktop Chromium payload','Bytes','Median JSON.parse ms','Retained parsed-object heap delta MiB'],[[r['file'],f"{r['response_bytes']:,}",f"{statistics.median(r['parse_ms']):.2f}",mb(r['retained_delta_bytes'])] for r in D['browser_measurements']['rows']])
text('## Modeled CPU scheduling requirements');text()
targets=[get('high-recommend',28),get('high-opt-opt'),get('high-experiment-64'),get('high-repeat-bundle')]
table(['Observed native demand','CPU seconds','Ideal at 2 vCPU s','Ideal at 4 vCPU s','Ideal at 8 vCPU s'],[[r['label'],fmt(r['cpu_seconds']),*[fmt(r['cpu_seconds']/n) for n in [2,4,8]]] for r in targets])
text('Division is arithmetic plausibility only. No 2/4/8-vCPU benchmark, throughput capacity, safe token quantity, reserve cost, new attempt floor, or production deployment number is certified. The 24-GiB host and 11.7-GiB VM are local test resources, not a supported hardware target.');text()
text('## Validation and production invariance');text()
table(['Final check','Result','Evidence / limitation'],[['Backend tests / race / vet','PASS','Unmodified backend full suites'],['Frontend unit/workflow tests / lint / build','PASS','Unmodified frontend'],['Real RF budget E2E','PASS','Fresh isolated backend; desktop-1440'],['Real optimizer deadline E2E','PASS','Separate fresh backend; desktop-1440'],['Workspace E2E','FAIL: 57 passed, 9 skipped, 1 failed','Existing cancellation feedback bounding-box assertion: x=100 versus expected 92 at workspace.spec.js:693'],['Targeted optimization E2E, twice','FAIL: 13 passed, 1 failed','Budget feedback hit the same intermittent 8-pixel x mismatch; cancellation then passed; both complete optimization journeys passed'],['Core Lab race / vet','PASS','Optional adapter full suites'],['Gated resource / cancel / concurrent / async suites','PASS','234 published native/eight/instrumented-Linux rows; normal production image HTTP measured separately'],['Gated resource race tests','PASS','Same/distinct/third clients, cancellation, queue drain; no detected race'],['Docs build / validation','PASS','Pandoc deprecation warnings; validation uses locked PyYAML in temporary venv after system Python lacked it'],['Version metadata / diff whitespace / tooling syntax / opt-in refusals','PASS','0.11.0; gated runners refuse execution without --run']]);text('The first baseline mock RF/deadline run skipped its eight real-backend cases. A combined real-server run also showed that the two files share the anchored ClientIP budget: the deadline request spent one attempt before the budget test expected a fresh window. Final isolated fresh-server runs passed separately. These initial outcomes are preserved, not reclassified as successes. Workspace failures remain unresolved because this is an audit and production UI changes are outside scope; no assertion was weakened.');text()
text('All tracked changes generated by workspace screenshot tests were restored to the clean starting baseline; the single new generated screenshot was removed. The pre-existing request-budget audit files/tooling remain intact. Production source, RF math, optimizer, frontend sequences, persistence, async manager, Dockerfile, and quotas are unchanged. Final tracked diff is empty. Only the two resource-study documents and opt-in tooling are added. Raw local measurement files remain in dedicated /tmp directories; the owned measurement container is removed after measurement.');text()
text('## Phase completion map');text()
table(['Requested phases','Coverage'],[['0–3','Baseline ledger, deployment classification, native/container environment snapshots, independently measured dimensions'],['4–9','Canonical 2.6/28 GHz routes, source bounds, single-parameter sweeps, supported high combinations and observed envelopes'],['10–13','Two-client mixes, same-IP/third-client rejection, high timeout and cancellation cases'],['14–16','Manager source audit, normal and alternate gated workers, overlap, 64-run jobs and queue cancellation'],['17–19','Individual/workflow response bytes, modeled link times, visible desktop parser/retained-object heap'],['20–23','Input/geometry/byte predictor trials, equal-profile Ankara domains and synthetic control'],['24–28','Authoritative workflow binding, anti-forgery, partial failure/retry/cancellation/refund semantics, frequency floor and resource dimensions'],['29–33','Local headroom, unbenchmarked hypothetical profiles, unchanged concurrency, six/eight workflow comparisons'],['34–39','Protected targets, candidate future architecture, explicit no numeric recommendation, eight-cell prerequisites, rejection and observability contract'],['40–43','Production invariance, classification F, both artifacts and final checks with failures disclosed']]);text()
text('**Final classification: F — More deployment data required.** No production numbers are certified. **Single recommended next action:** define an actual deployment profile and its load, latency, memory/CPU/link headroom, dataset complexity and background-worker requirements; replay this study on that target before selecting or implementing admission parameters.');text()
# Replace generated block idempotently.
p=ROOT/'docs/rf-resource-admission-study.md';s=p.read_text();marker='<!-- generated-measurement-tables -->';s=s.split(marker)[0].rstrip()+'\n\n'+marker+'\n\n'+'\n'.join(lines)+'\n';p.write_text(s)
