"""Map every requested final item to measured successor evidence."""
import json
from protocol import HERE,WORK,load

def items(result):
 r=result;b=r['budget'];mem=r['memory'];lock=load(HERE/'audit-lock.json');base=r['baseline'];cases=[q for q in b['cases'] if q['cardinality']==8];cycles=[q for q in cases if q['operation']=='cycle-boundary'];fits=b['product_fit'];valid=r['qualification_valid'];decision=r['classification']
 def op(name):
  failures=[f for f in r['capacity_failures'] if f['operation']==name];stats=r['operations'][name]
  return f"{'PASS' if stats['groups'] and not failures else 'FAIL / INCOMPLETE'}; {stats['groups']} groups; worst individual {stats['max_request_seconds']:.3f}s"
 def e2e(stage,name):
  q=r[stage][name];g=q['execution_guard'];return f"{g['discovered']} discovered / {g['executed']} executed / {g['passed']} passed / {g['failed']} failed / {g['skipped']} skipped; opt-in={g['opt_in_active']}"
 def command(name):return 'ATOM_REAL_E2E=1 '+' '.join(r['baseline_checks'][name]['command'])
 def binary(kind):
  q=r['binary_differential']['images'][kind];return f"binary {q['binary_sha256']}; image {q['image_id']}"
 normal=[q for q in r['background_results'] if q['operation'].startswith('async-')];sustained=[q for q in r['background_results'] if q['operation'].startswith('sustained-')]
 persistence=r['presentation_persistence'].get('records',[]);eight_p=next((q for q in persistence if q['cardinality']==8),{})
 network=next((q for q in eight_p.get('export_variants',[]) if q['composition']=='network-result-only'),{})
 journeys={}
 for n in [6,8]:
  journeys[n]={name:sorted({q['first_429_attempt'] or 'none' for q in b['cases'] if q['cardinality']==n and q['operation']=='journey-'+name},key=str) for name in ['A','B','C','D']}
 window=[q['remaining_window_client_estimate_seconds'] for q in cycles]
 cycle_bytes=max((q['logical_workflow_response_bytes'] for q in cycles),default=0)
 v={
 1:f"{base['branch']} @ {base['head']}; VERSION {base['version']}; prior uncommitted audit retained; exact status/diff in baseline.json",
 2:f"PASS; prior report/script/lock hashes and all {r['prior_raw_files_verified']} raw artifact hashes verified; prior D unchanged",
 3:command('rf_budget_e2e'),4:e2e('baseline_checks','rf_budget_e2e'),5:command('rf_deadline_e2e'),6:e2e('baseline_checks','rf_deadline_e2e'),
 7:'PASS; named JSON test records and opt-in verified; skipped/zero-test/missing-opt-in regressions rejected; pre-freeze chronology verified',
 8:r['hashes']['audit_lock'],9:r['hashes']['domain_manifest'],10:r['hashes']['run_plans'],11:r['hashes'].get('evidence_manifest','pending final index'),12:binary('standard'),13:binary('audit'),
 14:'Only MaxNetworkTowers 6→8 in disposable source; unchanged Dockerfile and shipping build flags',15:'Confirmed six',16:'HTTP 400 for seven/eight on all five network endpoints; six succeeds',
 17:'Go1.26.6 / Linux arm64 / CGO0 / cgroup v2',18:f"All {len(lock['batch_order'])} primary batches verify CPU2, GOMAXPROCS2, RAM4GiB, worker1, queue16, slots2/1, deadline60s, budget20/60s",19:'ankara-open-planning 2026.07; 161,784 footprint parts / 936,651 vertices / 451 inventory Cells; exact GeoJSON hashes verified',20:'Exact prior domain/run-plan bytes and all 36 fixture hashes; same six IDs/order and appended two IDs',21:'120 rays / 400m / 30dBm / 120° / 2.6 and28GHz / 20 and100MHz; legacy two-pass search; eight sequential single-Cell maps',22:f"{r['planned_groups']} planned / {r['observed_groups']} observed",
 23:op('evaluate'),24:op('optimize'),25:op('interference'),26:op('explain'),27:op('building-entry'),28:op('evaluate-maps'),29:op('optimize-maps'),30:op('cycle-boundary'),31:f"{r['worst_required_eight_cell_request']['elapsed_seconds']:.6f}s",32:f"{r['minimum_deadline_headroom_seconds']:.6f}s",33:f"{mem['peak_RSS_bytes']} bytes",34:f"{mem['peak_bytes']} bytes ({mem['peak_bytes']/(1<<30):.6f}GiB)",35:f"{100*mem['headroom_fraction']:.4f}% of hard limit remains",36:json.dumps(mem['events']),37:op('two-optimizers'),38:op('optimize-evaluate'),39:op('two-evaluates'),
 40:f"{sum(q['passed'] for q in normal)}/{len(normal)} PASS; actual uncached native overlap",41:f"{sum(q['passed'] for q in sustained)}/{len(sustained)} PASS; first30s activity and drain verified",42:f"{sum(q['final_tail_overlap'] is True for q in sustained)}/{len(sustained)} sustained tails overlap native background execution",43:json.dumps(r['largest_contention_inflation'],separators=(',',':')),
 44:f"{r['cancellation']['passed']}/{r['cancellation']['cases']} PASS; cancel100ms; max release observation {r['cancellation']['max_release_observation_seconds']:.6f}s",45:'PASS' if not r['capacity_failures'] else 'See capacity failures',46:f"{'PASS' if r['science']['stable'] else 'FAIL'}; {r['science']['exact_input_groups']} exact input groups; only Building Entry diagnostics.elapsed_ms excluded",47:f"{'PASS' if r['six_cell_preservation']['passed'] else 'FAIL'}; {r['six_cell_preservation']['responses_matching_frozen_W1']} exact frozen W1 response matches",
 48:'9 accepted; remaining11',49:'9 accepted; remaining11',50:'19 accepted; remaining1',51:'HTTP200, remaining0 in all four cycle boundary cases' if all(q['sequence'][19]['status']==200 for q in cycles) else 'FAIL',52:'HTTP429, remaining0, Retry-After/reset; before RF handler' if all(q['sequence'][20]['status']==429 for q in cycles) else 'FAIL',53:'18 accepted; remaining2',54:'PASS; separate connections share same ClientIP bucket' if b['shared_ip_and_distinct_ip_pass'] else 'FAIL',55:'PASS; fresh independent bucket, remaining19 after one request' if b['shared_ip_and_distinct_ip_pass'] else 'FAIL',56:'A/B/D succeed in both cardinalities; C first429 is absolute attempt21 in both, reached at the immediate Interference after 8C cycle+single Optimize (19+1+1), versus later follow-ups at6C (15+1+1 succeeds). '+json.dumps(journeys,separators=(',',':')),57:f"{min(window):.6f}–{max(window):.6f}s client-anchor estimate; integer shipping reset headers retained" if window else 'not measured',58:'PASS' if b['mechanical_pass'] else 'FAIL',59:fits,60:f"{r['eight_cell_summary']['largest_single_response_bytes']} bytes",61:f"Evaluate/maps {r['operations']['evaluate-maps']['largest_workflow_response_bytes']}; Optimize/maps {r['operations']['optimize-maps']['largest_workflow_response_bytes']}; logical cycle {cycle_bytes} bytes",
 62:'PASS; one network + eight sequential map calls, no duplicate/retry/StrictMode amplification' if r['frontend_smoke'].get('exit_code')==0 else 'FAIL / PENDING',63:'PASS; numbering1–8, selection, Setup, Results, Solutions, Review, scroll, report' if r['frontend_smoke'].get('exit_code')==0 else 'FAIL / PENDING',64:f"Network-result-only8 round-trip={network.get('export_import_pass')}; {network.get('exported_bytes')} bytes; full ray variants hit existing guards; no new gate",65:'PASS' if r['operational_pass'] else 'FAIL / INVALID',66:json.dumps(r['methodology_violations']),67:'None' if r['observed_groups']==r['planned_groups'] and r['publication_ready'] else 'Final evidence/checks pending',68:f"{decision} — {r['decision']}",69:'Yes, exact frozen Profile A scope' if r['operational_pass'] and valid else 'No',70:'Yes' if fits=='PRODUCT BLOCKER' else 'No',71:'Yes',72:'Separate promotion task justified' if decision=='A' else 'Promotion blocked; policy design first' if decision=='B' else 'No',73:'Yes; separate task' if decision=='B' else 'Not the next action',74:'Paused; estimator/adaptive admission not reopened',75:'Observation-only',76:'PASS; production source/build/policy/persistence/fingerprints unchanged',77:('Budget: '+e2e('final_checks','rf_budget_e2e')+'; Deadline: '+e2e('final_checks','rf_deadline_e2e')) if r['final_checks'] else 'pending',78:'Keep VERSION0.11.0; no release/tag/publish',79:'New successor report MD/JSON/HTML and scripts; CHANGELOG.md, docs build reference, generated changelog/search index updated; prior audit unchanged',80:str(WORK)+'; SHA256/size/category/group index and separate hashed archive outside Git',81:'Ten baseline and fifteen final quality commands; protocol/guard tests; real cardinality, overlap, cancellation, science, evidence controls',82:r['freeze_decision'],83:r['next_action']}
 labels={int(q.split('. ',1)[0]):q.split('. ',1)[1] for q in (WORK/'request.txt').read_text().split('FINAL RESPONSE — REQUIRED')[1].splitlines() if q[:1].isdigit() and '. ' in q}
 assert sorted(v)==list(range(1,84))==sorted(labels)
 return [{'number':n,'label':labels[n],'result':v[n]} for n in range(1,84)]
