#!/usr/bin/env python3
"""Generate runtime policy bindings from policy/rf-policy.json."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "policy/rf-policy.json"


def go_number(value: int | float) -> str:
    return json.dumps(value)


def format_go(source: str) -> str:
    result = subprocess.run(
        ["gofmt"],
        input=source,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def load_policy() -> dict:
    policy = json.loads(SOURCE.read_text(encoding="utf-8"))
    scenarios = policy["core_lab_scenarios"]
    technologies = policy["technologies"]
    if policy.get("version") != 1:
        raise SystemExit("unsupported RF policy version")
    if len({item["id"] for item in scenarios}) != len(scenarios):
        raise SystemExit("core lab scenario IDs must be unique")
    if [item["id"] for item in technologies] != ["4g", "5g", "6g"]:
        raise SystemExit("technologies must be ordered as 4g, 5g, 6g")
    for left, right in zip(technologies, technologies[1:]):
        if left["maximum_frequency_ghz"] != right["minimum_frequency_ghz"]:
            raise SystemExit("technology frequency ranges must be contiguous")
    rf_profile = policy["rf_profile"]
    if rf_profile.get("schema_version") != 1:
        raise SystemExit("unsupported RF profile schema version")
    for key in ("duplex_modes", "horizontal_patterns", "vertical_patterns"):
        values = rf_profile[key]
        identifiers = [item if isinstance(item, str) else item["id"] for item in values]
        if not identifiers or len(set(identifiers)) != len(identifiers):
            raise SystemExit(f"RF profile {key} must contain unique values")
    return policy


def render_scenario_go(package: str, policy: dict, function_name: str) -> str:
    ids = [item["id"] for item in policy["core_lab_scenarios"]]
    entries = "\n".join(f'\t"{scenario}": {{}},' for scenario in ids)
    return format_go(f'''// Code generated by scripts/generate_policy.py; DO NOT EDIT.

package {package}

const policyMaxTowerIDBytes = {policy["limits"]["tower_id_bytes"]}

var allowedCoreLabScenarios = map[string]struct{{}}{{
{entries}
}}

func {function_name}(scenario string) bool {{
\t_, ok := allowedCoreLabScenarios[scenario]
\treturn ok
}}
''')


def render_raytracer_go(policy: dict) -> str:
    defaults = policy["defaults"]
    limits = policy["limits"]
    tech = {item["id"]: item for item in policy["technologies"]}
    constants = {
        "DefaultStaticSimulationRays": defaults["static_simulation_rays"],
        "DefaultNetworkOptimizationRays": defaults["network_optimization_rays"],
        "DefaultRadiusMeters": defaults["radius_m"],
        "DefaultFrequencyGHz": defaults["frequency_ghz"],
        "DefaultTxPowerDBm": defaults["tx_power_dbm"],
        "DefaultBeamWidthDeg": defaults["beam_width_deg"],
        "DefaultCalibrationOffsetDB": defaults["calibration_offset_db"],
        "DefaultInterferenceBandwidthLTE": tech["4g"]["default_bandwidth_mhz"],
        "DefaultInterferenceBandwidthNR": tech["5g"]["default_bandwidth_mhz"],
        "DefaultInterferenceLoadFactor": defaults["interference_load_factor"],
        "DefaultInterferenceReuseFactor": defaults["reuse_factor"],
        "DefaultInterferenceNoiseFigure": defaults["noise_figure_db"],
        "DefaultInterferenceSpacingM": defaults["sample_spacing_m"],
        "DefaultRecommendationResults": defaults["recommendation_results"],
        "LTEFrequencyMaxGHz": tech["4g"]["maximum_frequency_ghz"],
        "NRFrequencyMaxGHz": tech["5g"]["maximum_frequency_ghz"],
        "MaxTowerIDBytes": limits["tower_id_bytes"],
        "MinLongitude": limits["longitude_min"],
        "MaxLongitude": limits["longitude_max"],
        "MinLatitude": limits["latitude_min"],
        "MaxLatitude": limits["latitude_max"],
        "MinSimulationRays": limits["rays_min"],
        "MaxSimulationRays": limits["rays_max"],
        "MinRadiusMeters": limits["radius_m_min"],
        "MaxRadiusMeters": limits["radius_m_max"],
        "MaxFrequencyGHz": limits["frequency_ghz_max"],
        "MinTxPowerDBm": limits["tx_power_dbm_min"],
        "MaxTxPowerDBm": limits["tx_power_dbm_max"],
        "MinBeamWidthDeg": limits["beam_width_deg_min"],
        "MaxBeamWidthDeg": limits["beam_width_deg_max"],
        "MinCalibrationOffsetDB": limits["calibration_offset_db_min"],
        "MaxCalibrationOffsetDB": limits["calibration_offset_db_max"],
        "MinNetworkTowers": limits["network_towers_min"],
        "MaxNetworkTowers": limits["network_towers_max"],
        "MaxRecommendationTowers": limits["recommendation_towers_max"],
        "MinMeasurementTowers": limits["measurement_towers_min"],
        "MaxMeasurementTowers": limits["measurement_towers_max"],
        "MinRecommendationResults": limits["recommendation_results_min"],
        "MaxRecommendationResults": limits["recommendation_results_max"],
        "MinInterferenceLoadFactorExclusive": limits["interference_load_factor_min_exclusive"],
        "MaxInterferenceLoadFactor": limits["interference_load_factor_max"],
        "MinNoiseFigureDB": limits["noise_figure_db_min"],
        "MaxNoiseFigureDB": limits["noise_figure_db_max"],
        "MinSampleSpacingM": limits["sample_spacing_m_min"],
        "MaxSampleSpacingM": limits["sample_spacing_m_max"],
        "RFProfileSchemaVersion": policy["rf_profile"]["schema_version"],
        "DefaultAntennaGainDBi": defaults["antenna_gain_dbi"],
        "DefaultSystemLossDB": defaults["system_loss_db"],
        "DefaultAntennaHeightM": defaults["antenna_height_m"],
        "DefaultMechanicalDowntiltDeg": defaults["mechanical_downtilt_deg"],
        "DefaultElectricalDowntiltDeg": defaults["electrical_downtilt_deg"],
        "DefaultOrientationDeg": defaults["orientation_deg"],
        "DefaultReceiverHeightM": defaults["receiver_height_m"],
        "DefaultReceiverSensitivityDBm": defaults["receiver_sensitivity_dbm"],
        "MaxRFProfileTextBytes": limits["profile_text_bytes"],
        "MinBandwidthMHz": limits["bandwidth_mhz_min"],
        "MaxBandwidthMHz": limits["bandwidth_mhz_max"],
        "MinAntennaGainDBi": limits["antenna_gain_dbi_min"],
        "MaxAntennaGainDBi": limits["antenna_gain_dbi_max"],
        "MinSystemLossDB": limits["system_loss_db_min"],
        "MaxSystemLossDB": limits["system_loss_db_max"],
        "MinAntennaHeightM": limits["antenna_height_m_min"],
        "MaxAntennaHeightM": limits["antenna_height_m_max"],
        "MinDowntiltDeg": limits["downtilt_deg_min"],
        "MaxDowntiltDeg": limits["downtilt_deg_max"],
        "MaxRFProfileReuseFactor": limits["reuse_factor_max"],
        "MinPCI": limits["pci_min"],
        "MaxLTEPCI": limits["pci_lte_max"],
        "MaxNRPCI": limits["pci_nr_max"],
        "MinReceiverHeightM": limits["receiver_height_m_min"],
        "MaxReceiverHeightM": limits["receiver_height_m_max"],
        "MinReceiverSensitivityDBm": limits["receiver_sensitivity_dbm_min"],
        "MaxReceiverSensitivityDBm": limits["receiver_sensitivity_dbm_max"],
    }
    lines = "\n".join(f"\t{name} = {go_number(value)}" for name, value in constants.items())
    return format_go(f'''// Code generated by scripts/generate_policy.py; DO NOT EDIT.

package raytracer

const (
{lines}
)

func NetworkTechnologyForFrequency(frequencyGHz float64) string {{
\tswitch {{
\tcase frequencyGHz < LTEFrequencyMaxGHz:
\t\treturn "4g"
\tcase frequencyGHz < NRFrequencyMaxGHz:
\t\treturn "5g"
\tdefault:
\t\treturn "6g"
\t}}
}}

func DefaultFrequencyForTechnology(networkTech string) float64 {{
\tswitch networkTech {{
\tcase "4g":
\t\treturn {go_number(tech["4g"]["default_frequency_ghz"])}
\tcase "5g":
\t\treturn {go_number(tech["5g"]["default_frequency_ghz"])}
\tdefault:
\t\treturn {go_number(tech["6g"]["default_frequency_ghz"])}
\t}}
}}

func DefaultBandForTechnology(networkTech string) string {{
	switch networkTech {{
	case "4g":
		return {json.dumps(tech["4g"]["default_band"])}
	case "5g":
		return {json.dumps(tech["5g"]["default_band"])}
	default:
		return {json.dumps(tech["6g"]["default_band"])}
	}}
}}

func DefaultDuplexModeForTechnology(networkTech string) string {{
	if networkTech == "4g" {{
		return {json.dumps(tech["4g"]["default_duplex_mode"])}
	}}
	return {json.dumps(tech["5g"]["default_duplex_mode"])}
}}

func DefaultBandwidthForTechnology(networkTech string) float64 {{
	switch networkTech {{
	case "4g":
		return {go_number(tech["4g"]["default_bandwidth_mhz"])}
	case "5g":
		return {go_number(tech["5g"]["default_bandwidth_mhz"])}
	default:
		return {go_number(tech["6g"]["default_bandwidth_mhz"])}
	}}
}}

func IsAnalysisTechnology(networkTech string) bool {{
\treturn networkTech == "4g" || networkTech == "5g"
}}

func FrequencyMatchesTechnology(networkTech string, frequencyGHz float64) bool {{
\treturn frequencyGHz > 0 && NetworkTechnologyForFrequency(frequencyGHz) == networkTech
}}
''')


def render_frontend(policy: dict) -> str:
    scenarios = json.dumps(policy["core_lab_scenarios"], indent=2)
    technologies = json.dumps(policy["technologies"], indent=2)
    defaults = policy["defaults"]
    limits = json.dumps(policy["limits"], indent=2)
    rf_profile = policy["rf_profile"]
    ui_defaults = {
        "frequencyGHz": defaults["frequency_ghz"],
        "txPowerDbm": defaults["tx_power_dbm"],
        "rayCount": defaults["frontend_simulation_rays"],
        "radiusMeters": defaults["radius_m"],
        "azimuthDeg": defaults["azimuth_deg"],
        "beamWidthDeg": defaults["beam_width_deg"],
        "interferenceBandwidthMHz": next(item["default_bandwidth_mhz"] for item in policy["technologies"] if item["id"] == "5g"),
        "cellLoadPct": defaults["interference_load_factor"] * 100,
        "reuseFactor": defaults["reuse_factor"],
        "noiseFigureDb": defaults["noise_figure_db"],
        "sampleSpacingMeters": defaults["sample_spacing_m"],
        "calibrationOffsetDb": defaults["calibration_offset_db"],
    }
    profile_defaults = {
        "schemaVersion": rf_profile["schema_version"],
        "band": next(item["default_band"] for item in policy["technologies"] if item["id"] == "5g"),
        "bandwidthMHz": next(item["default_bandwidth_mhz"] for item in policy["technologies"] if item["id"] == "5g"),
        "channelId": "CH-1",
        "duplexMode": next(item["default_duplex_mode"] for item in policy["technologies"] if item["id"] == "5g"),
        "antennaGainDbi": defaults["antenna_gain_dbi"],
        "systemLossDb": defaults["system_loss_db"],
        "antennaHeightM": defaults["antenna_height_m"],
        "mechanicalDowntiltDeg": defaults["mechanical_downtilt_deg"],
        "electricalDowntiltDeg": defaults["electrical_downtilt_deg"],
        "orientationDeg": defaults["orientation_deg"],
        "horizontalPatternId": defaults["horizontal_pattern_id"],
        "verticalPatternId": defaults["vertical_pattern_id"],
        "loadFactor": defaults["interference_load_factor"],
        "reuseFactor": defaults["reuse_factor"],
        "pci": None,
        "receiverHeightM": defaults["receiver_height_m"],
        "receiverSensitivityDbm": defaults["receiver_sensitivity_dbm"],
    }
    return f'''// Code generated by scripts/generate_policy.py; DO NOT EDIT.

export const CORE_LAB_SCENARIOS = Object.freeze({scenarios});

export const NETWORK_TECHNOLOGIES = Object.freeze({technologies});

export const NETWORK_TECH_OPTIONS = Object.freeze(NETWORK_TECHNOLOGIES.map((technology) => ({{
  id: technology.id,
  label: technology.label,
  frequencyGHz: technology.default_frequency_ghz,
  defaultBandwidthMHz: technology.default_bandwidth_mhz,
  bandwidthsMHz: technology.bandwidths_mhz,
}})));

export const DEFAULT_SIMULATION = Object.freeze({json.dumps(ui_defaults, indent=2)});

export const RF_PROFILE_SCHEMA_VERSION = {rf_profile["schema_version"]};

export const DEFAULT_RF_PROFILE = Object.freeze({json.dumps(profile_defaults, indent=2)});

export const RF_PROFILE_OPTIONS = Object.freeze({json.dumps({
        "duplexModes": rf_profile["duplex_modes"],
        "horizontalPatterns": rf_profile["horizontal_patterns"],
        "verticalPatterns": rf_profile["vertical_patterns"],
    }, indent=2)});

export const DEFAULT_RECOMMENDATION_RESULTS = {defaults["recommendation_results"]};

export const POLICY_LIMITS = Object.freeze({limits});

export function networkTechnologyForFrequency(frequencyGHz) {{
  const value = Number(frequencyGHz);
  if (value < NETWORK_TECHNOLOGIES[0].maximum_frequency_ghz) return "4g";
  if (value < NETWORK_TECHNOLOGIES[1].maximum_frequency_ghz) return "5g";
  return "6g";
}}
'''


def generated_files(policy: dict) -> dict[Path, str]:
    return {
        ROOT / "backend-go/raytracer/policy_generated.go": render_raytracer_go(policy),
        ROOT / "backend-go/core_lab_policy_generated.go": render_scenario_go("main", policy, "isAllowedCoreLabScenario"),
        ROOT / "core-lab-adapter/policy_generated.go": render_scenario_go("main", policy, "isAllowedScenario"),
        ROOT / "frontend-react/src/generated/policy.js": render_frontend(policy),
    }


def stale_files(files: dict[Path, str]) -> list[Path]:
    return [
        path
        for path, content in files.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated bindings are stale")
    args = parser.parse_args()
    files = generated_files(load_policy())
    if args.check:
        stale = stale_files(files)
    else:
        stale = []
    for path, content in files.items():
        if args.check:
            continue
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        raise SystemExit("stale generated policy bindings: " + ", ".join(str(path.relative_to(ROOT)) for path in stale))
    print("RF policy bindings are current")


if __name__ == "__main__":
    main()
