#!/usr/bin/env python3
"""Render the audit narrative and compact finite-sample evidence tables."""
import argparse,json,pathlib,statistics
ROOT=pathlib.Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--input',default=str(ROOT/'docs/auto-resource-geometry-calibration.json'));p.add_argument('--output',default=str(ROOT/'docs/auto-resource-geometry-calibration.md'));a=p.parse_args();r=json.loads(pathlib.Path(a.input).read_text());lines=[]
def add(s=''):lines.append(s)
def table(headers,rows):
 add('| '+' | '.join(headers)+' |');add('| '+' | '.join(['---']*len(headers))+' |')
 for row in rows:add('| '+' | '.join(str(x) for x in row)+' |')
 add()
def f(x):return f'{x:.3f}' if isinstance(x,float) else str(x)
def pct(x):return '—' if x is None else f'{100*x:.1f}%'
add('# Auto Resource Geometry Calibration')
add()
add('**Decision: no admission estimator ready. Freeze this audit and keep Auto observation-only.** This development-VM sample tests geometry metadata and interpretable predictors; it does not certify production capacity, margins, workload classes or adaptive policy.')
add()
add('## Starting baseline and boundaries')
add()
b=r['environment']['baseline'];add(f"2026-10-04 (Europe/Istanbul), clean `main`, HEAD `{b['head']}`, VERSION `{b['version']}`. Initial `git status --short` and `git diff --stat` were empty. Previous Auto foundation, calibration and capacity reports are preserved. No tracked backend/frontend, policy, fingerprint, persistence or dataset files changed.")
add()
add('Fixed policy remains **20 protected attempts / ClientIP / anchored 60s; concurrency 2 global /1 client; RF deadline 60s; selected Cell cap 6; experiment workers 1, queue 16**. Auto only observes. No admission, GOMAXPROCS, RF-science, search/Pareto, frontend shape or user controls were changed. VERSION remains 0.11.0; recommend **no release**, internal calibration only.')
add()
add('## Resource profiles')
add()
vm=r['environment']['vm'];add(f"Sequential Docker cgroup-v2 profiles on a shared {vm['NCPU']}-CPU / {vm['MemTotal']/(1<<30):.3f} GiB Linux arm64 development VM. Existing `atom-app` was preserved; no calibration ports published. The unchanged image provides the container; the measured disposable instrumented test binary uses the recorded local Go toolchain, distinct from the image server's Go 1.26.6. Constraints were checked with existing Auto detection in the actual measured process before RF work.")
add()
rows=[]
for name,pf in r['profiles'].items():
 cpu=pf['cpu'];mem=pf['memory'];rows.append([name,cpu['visible_logical_cpus']['value'],cpu['gomaxprocs']['value'],cpu['cgroup_quota_cores']['value'] or cpu['cgroup_quota_cores']['state'],f(mem['cgroup_limit_bytes']['value']/(1<<30)) if mem['cgroup_limit_bytes']['value'] else mem['cgroup_limit_bytes']['state'],f(mem['effective_observed_limit_bytes']['value']/(1<<30)),pf['runtime']['go_version']])
table(['Profile','Visible CPU','GOMAXPROCS','Quota cores','Cgroup GiB','Observed ceiling GiB','Runtime'],rows)
add('A =2CPU/4GiB, B=4CPU/8GiB, D=default without explicit quota/limit. No 8CPU rerun: geometry/load is the study variable. Host-bounded default and quotas promise no exclusive resources. Full Auto provenance, diagnostic fingerprints, external Docker constraints, container exit/OOM state are retained in JSON.')
add()
add('## Deterministic public-planning domains')
add()
add(r['domain_selection']['method'])
add()
add('Select the hardest high-density pair first, followed by dense, medium and sparse pairs; this avoids exhausting disjoint choices at the high end. A ranking target is a construction rule, not a universal density threshold. Counts include all intersecting footprint parts and complete outer-ring vertices, not clipped geometry. Geometric edge count excludes a duplicated closing vertex; actual engine edge-check counters may also include degenerate closing segments. Domain area is the conservative enclosing rectangle, including gaps between towers; densities are rectangle statistics. All eight 800m selection rectangles are disjoint, so overlaps do not dominate samples. Selection/splits precede RF timings. Exact public planning coordinates and selected tower IDs occur only in audit artifacts, never user-location logs.')
add()
ds=r['domain_selection']['selected'];table(['Domain','Split','Rank','Footprint parts','Logical buildings','Vertices','Edges','Area km²','Parts/km²','Vertices/km²','Max / median vertices'],[[d['id'],d['split'],d['rank'],d['stats']['footprints'],d['stats']['logical_buildings'],d['stats']['vertices'],d['stats']['edges'],f(d['stats']['area_km2']),f(d['stats']['footprints_per_km2']),f(d['stats']['vertices_per_km2']),f"{d['stats']['max_vertices']} / {d['stats']['median_vertices']}"] for d in ds])
add(f"Dataset `{r['domain_selection']['dataset']['id']}` version `{r['domain_selection']['dataset']['version']}`: {r['domain_selection']['global_footprints']:,} indexed footprint parts, {r['domain_selection']['global_vertices']:,} vertices, {r['domain_selection']['inventory_cells']} inventory Cells. Dataset SHA256 identity is retained. Only this real installed pack exists in the repository/default app; the sample-pack is synthetic test data and acquisition manifests are layer audits. No second production dataset or synthetic scaling experiment was invented. Global counts are constant and their cross-dataset predictive value is **unidentifiable**.")
add()
add('## Preflight prototype and cost')
add()
add(r['methodology']['preflight'])
add()
add('Both plain bbox candidate count and footprint/vertex/edge metadata are measured at 100, 400 and 800m for one/six Cells, all eight domains, all profiles: five batches of 100 lookups each. Metadata currently sorts polygon complexity for the diagnostic median; this is test-only and not necessary in a future bounded count query. Reads allocate result slices and visit every bbox candidate; enumeration grows with candidate count and is not a constant-time guarantee. Existing production indexes are unchanged.')
add()
pr=r['preflight'];table(['Profile','Query','Median batch-average wall µs','Worst batch-average wall µs','Worst allocation KiB/query'],[[profile,kind,f(statistics.median(x['wall']['median'] for x in pr if x['profile']==profile and x['kind']==kind)*1e6),f(max(x['wall']['max'] for x in pr if x['profile']==profile and x['kind']==kind)*1e6),f(max(x['allocation']['max'] for x in pr if x['profile']==profile and x['kind']==kind)/1024)] for profile in ['A','B','D'] for kind in ['bbox-count','footprint-vertices-edges']])
add('Use per-row preflight/RF ratios in JSON when interpreting very cheap Surface or sparse Simulate operations: a cheap scan is not necessarily much cheaper than every endpoint. The study measures the diagnostic full-ring scan; it does not introduce an enforcing query.')
add()
add('## Matrix and measurement protocol')
add()
for k in ['rf','matrix','supplement','feature_audit','cache','sampling','omissions']:add(f"**{k}:** {r['methodology'][k]}");add()
add('Canonical operations: Simulate, Evaluate, Evaluate+six maps, Optimize, Optimize+six returned-azimuth maps, Interference, Explain Cell, Optimize Azimuth, Coverage Surface, Recommendation and Building Entry. Six Cells where supported; one for single-cell endpoints; Recommendation uses its supported five-Cell maximum. Surface grid=25m fixed across cases. Recommendation polygon encloses the selected six inventory positions plus20m and includes all inventory candidates there; candidate count/relative Cell spacing vary with geography and are disclosed confounders. Explain prerequisite Optimize is excluded from its interval.')
add()
add(f"{r['summary']['run_count']} recorded case runs, {r['summary']['isolated_group_count']} isolated groups, {r['summary']['mixed_run_count']} mixed scenarios. Five repeats for ordinary canonical cases; three for Optimize, Optimize+maps, Explain and Recommendation, and for variants/mixed cases (expensive repeated optimizer prerequisites and searches make the full five-pass matrix costly). Min/median/max, spread and population CV are finite sample summaries, **not percentile distributions**. A malformed Recommendation audit payload stopped an initial pilot; corrected pilot timings are excluded. No supported request was reduced to make a profile pass.")
add()
add('### Canonical repeats across all geometry bands (D)')
add()
table(['Domain','GHz','Operation','n','Wall min / median / max s','Wall CV','CPU min / median / max s','Bytes median'],[[g['domain'],g['frequency_ghz'],g['operation'],g['repeat_count'],f"{g['statistics']['wall_seconds']['min']:.3f} / {g['statistics']['wall_seconds']['median']:.3f} / {g['statistics']['wall_seconds']['max']:.3f}",pct(g['statistics']['wall_seconds']['coefficient_of_variation']),f"{g['statistics']['cpu_seconds']['min']:.3f} / {g['statistics']['cpu_seconds']['median']:.3f} / {g['statistics']['cpu_seconds']['max']:.3f}",f"{g['response_bytes']:.0f}"] for g in r['isolated_groups'] if g['profile']=='D' and g['split']=='calibration' and g['level']=='normal'])
add('## Location effect and hardware effect')
add()
add('All RF/search settings are identical across domains within a workload; inventory geometry and relative Cell spacing change. These are location effects, not a causal density-only experiment. Single-cell maps use the anchor geometry; network cases use six different real inventory positions. A sparse/dense label for the network envelope need not order the one-Cell envelope or path viability.')
add()
table(['Profile','GHz','Operation','Sparse wall s','Dense wall s','Wall dense/sparse','Sparse CPU s','Dense CPU s','CPU dense/sparse'],[[x['profile'],x['frequency_ghz'],x['operation'],f(x['sparse_wall']),f(x['dense_wall']),f(x['wall_inflation']),f(x['sparse_cpu']),f(x['dense_cpu']),f(x['cpu_inflation'])] for x in r['geometry_effects']])
table(['Domain','Operation','A/B wall ratio','A/D wall ratio'],[[x['domain'],x['operation'],f(x['A_to_B_wall_ratio']),f(x['A_to_D_wall_ratio'])] for x in r['hardware_effects']])
add('Compare the location ratios with each operation’s A/B ratio above. No universal claim that density dominates CPU is supported. A density-only monotone estimator is unsafe: candidate geometry, polygon complexity, live paths, frequency and deterministic search behavior contribute differently. Pearson correlations of grouped D medians with geometry/rays/radius/area appear per operation/target in JSON; constant Cell count is null, not fabricated evidence. Correlated footprint/vertex/edge features do not prove admission safety.')
add()
add('## Warm runs, GC and throttling')
add()
warm=r['warm_run_comparisons'];ratios=[x['first_to_repeat_ratio'] for x in warm];add(f"First-measured / subsequent-median wall ratio across groups: median {statistics.median(ratios):.3f}x, range {min(ratios):.3f}–{max(ratios):.3f}x. The preflight stage loads the pack; the RF stage reloads the same pack in that process. Its index is fully loaded before every measured RF request, which also follows an explicit domain scan. The earlier stage’s unreachable heap may await GC; startup/load CPU was not isolated. This is warmed-process characterization; OS page cache/startup, scheduler, host activity and heap state are not independently controlled. Request-local optimizer caches are rebuilt normally. There is no retained frontend or experiment-cache speedup in the measured async cases.")
add()
add(f"{r['summary']['gc_events']} GC cycles occurred across measured intervals; maximum cumulative stop-the-world pause / wall is {100*r['summary']['maximum_gc_pause_fraction_of_wall']:.2f}%. GC pause is only one part of GC cost; concurrent mark/assist and scheduler effects cannot be separated by pause totals. Per-row heap before/after, cumulative allocations, GC counts/pauses and sampled heap are retained. {r['summary']['rows_with_throttling']} rows had throttled periods. Cgroup CPU usage, periods, throttled periods/duration and memory events are retained. Throttled duration is accumulated accounting, not direct wall slowdown; concurrency CPU is aggregate, not attributable to individual operations.")
add()
add('## Repeated mixed load and tails')
add()
add('Each profile repeats three times: Optimize+uncached16-run experiment; Evaluate+uncached16-run experiment; two distinct-client Optimizers; Optimize+Evaluate. Each scenario is tested on sparse/dense domains at2.6GHz with unchanged 2/1 RF slots and one async worker. Job status must be running before interactive work; actual timestamps must overlap. Aggregate CPU/GC/memory includes both jobs. Async work is ordinary Simulate azimuth sweep, not background network optimization; finite overlap does not certify a sustained queue.')
add()
table(['Profile','Domain','Scenario','Operation','Isolated median s','Mixed median s','Mixed max s','Median inflation','Max inflation'],[[x['profile'],x['domain'],x['scenario'],x['operation'],f(x['isolated_median']),f(x['mixed']['median']),f(x['mixed']['max']),f(x['median_inflation']),f(x['max_inflation'])] for x in r['mixed_load']])
worst=max(r['mixed_load'],key=lambda x:x['max_inflation']);add(f"Worst observed inflation: {worst['max_inflation']:.3f}x ({worst['profile']}, {worst['domain']}, {worst['scenario']}, {worst['operation']}). Minimum individual RF deadline headroom across all runs: {r['summary']['minimum_request_deadline_headroom']:.3f}s. Bundle duration is not a single-request deadline. Throttle/GC/overlap per scenario is in JSON; shared-host noise remains an unresolved causal contributor.")
add()
add('## Operation-specific predictors and held-out gate')
add()
add(r['methodology']['safety_gate'])
add()
add('Fit log-cost ridge linear predictors independently per operation and target, using medians of repeat groups. Features are rays/radius/frequency (ray count omitted for Interference, Surface and Building Entry) plus one of footprint count, vertices, edges, density+area, or footprint+vertices; a parameter-only baseline is compared. Ray-only unchanged-compute controls for those three operations are excluded from fitting/scoring. These are exploratory source-informed predictors, not preregistered models; partial held-out results were inspected before the source-based removal of unused ray count, so fresh locked validation is required. Select the family by leave-one-calibration-domain-out log RMSE; standardization and coefficients fit only training rows. All four held-out locations and the180-ray/600m setting stay untouched. Hardware A/B transfer is also scored against the D-fit model and recorded separately. The CPU capacity signal is observed but a capacity coefficient cannot be learned from D-only fitting; no universal wall=CPU/cores guarantee is claimed. Exact formulas, feature transforms, means/scales, coefficients, all candidate CV scores and worst-case identifiers are in JSON.')
add()
for target,title in [('cpu_seconds','CPU'),('wall_seconds','Wall time in profile D'),('spatial_candidates','Spatial candidate work'),('response_bytes','Response bytes'),('allocation_bytes','Allocations'),('rss_sampled_max_bytes','Sampled absolute RSS')]:
 add('### '+title);add()
 rr=[]
 for op,ts in r['models'].items():
  m=ts[target]
  if 'model' not in m:rr.append([op,'unidentifiable','—','—','—','—','—','—']);continue
  err=m['held_out'];rr.append([op,m['selected_family'],pct(err['median_absolute_relative_error']),f(err['max_underestimation_actual_over_predicted']),pct(err['max_overestimation_fraction']),f(m['calibration_only_margin']),pct(m['held_out_with_calibration_margin']['underestimate_percent']),m['readiness']])
 table(['Operation','Family','Median absolute error','Worst actual/predicted','Worst overestimate','Calibration CV margin','Underestimates after margin','Numeric gate'],rr)
add('Held-out errors are measured relative to actual demand; worst actual/predicted reports the required retrospective multiplier. A margin that covers this sample is not a production bound. The JSON separates held-out domain errors, held-out setting errors and A/B hardware transfer; one combined error can hide extrapolation failure. Numeric gate success means a promising pilot, never admission certification. Geometry targets are repeated spatial-candidate/edge work, not an assertion that bbox count equals exact RF intersections.')
add()
add(f"Worst un-margined CPU underprediction across operation estimators: {r['summary']['worst_cpu_heldout_underprediction_factor']:.3f}x actual/predicted; response: {r['summary']['worst_response_heldout_underprediction_factor']:.3f}x. Both may be different cases than the worst latency. Frequency/path survival and grid/output form explain why response bytes require a separate model; dense geometry need not produce larger output.")
add()
geometry_worst=max((m['spatial_candidates']['held_out']['max_underestimation_actual_over_predicted'],op) for op,m in r['models'].items() if 'model' in m['spatial_candidates'])
add(f"The worst spatial-candidate predictor is {geometry_worst[1]}: {geometry_worst[0]:,.1f}x actual/predicted. This is a catastrophic zero-to-positive extrapolation of the exploratory log-target model (zero training work is floored at1e-9), not an observed geometry-cost explosion. Reject this model and its margins; a zero-aware candidate-work model would need a new locked validation. The directly enumerated bbox metadata itself remains deterministic and conservatively includes complete footprint parts.")
add()
add('Memory: allocation totals are cumulative work, not live demand. Absolute sampled RSS includes loaded dataset, retained heap and recorder response copies; it is order-dependent, can miss spikes and is not incremental memory reservation. Cgroup current includes file/kernel charges; cumulative lifetime peak includes startup/previous cases. Existing app/OS/VM overhead and queued job retention remain unmeasured. The tables quantify exploratory predictors but cannot establish a conservative live-memory envelope.')
add()
add('The table’s median error is median absolute relative error. Signed median errors, maximum shortfall relative to actual, percentage of raw underestimates and setting/domain splits are retained in JSON. Required margins must be compared with calibration-only CV margins, not fitted after seeing held-out data.')
add()
add('### Margin stability across held-out settings and hardware')
add()
table(['Operation','CPU calibration margin','CPU domain actual/pred max','CPU held-setting actual/pred max','CPU A actual/pred max','CPU B actual/pred max'],[[op,f(m['cpu_seconds']['calibration_only_margin']),f(m['cpu_seconds']['held_out_domains']['max_underestimation_actual_over_predicted']) if m['cpu_seconds']['held_out_domains'] else '—',f(m['cpu_seconds']['held_out_settings']['max_underestimation_actual_over_predicted']) if m['cpu_seconds']['held_out_settings'] else '—',f(m['cpu_seconds']['hardware_transfer_errors']['A']['max_underestimation_actual_over_predicted']) if m['cpu_seconds']['hardware_transfer_errors']['A'] else '—',f(m['cpu_seconds']['hardware_transfer_errors']['B']['max_underestimation_actual_over_predicted']) if m['cpu_seconds']['hardware_transfer_errors']['B'] else '—'] for op,m in r['models'].items()])
add('Some operation/margin pairs may pass this finite pilot gate, but stability is not established across search policies, new datasets, sustained load and deployment hosts. Large calibration margins or validation exceedances reject that predictor; no retrospective held-out covering multiplier is selected for production.')
add()
add('## Internal cost bands')
add()
add('Four CPU-prediction quartile bands are set using calibration data only. Held-out classification uses the unchanged predictor/cutoffs; actual CPU/RSS/bytes ranges and exceedances of training maxima are retained per band in JSON. CPU groups do not jointly bound memory/response, and broad overlapping ranges cannot support one multi-resource cost class. **Reject these cost bands for admission or product names.**')
add()
table(['Band','Cal CPU min–max s','Held CPU min–max s','Cal RSS min–max MiB','Cal bytes min–max','Held exceedances CPU / RSS / bytes'],[[c['band'],f"{c['training_bounds']['cpu_seconds']['min']:.3f}–{c['training_bounds']['cpu_seconds']['max']:.3f}",f"{c['held_out_bounds']['cpu_seconds']['min']:.3f}–{c['held_out_bounds']['cpu_seconds']['max']:.3f}" if c['held_out_bounds']['cpu_seconds'] else '—',f"{c['training_bounds']['rss_sampled_max_bytes']['min']/(1<<20):.1f}–{c['training_bounds']['rss_sampled_max_bytes']['max']/(1<<20):.1f}",f"{c['training_bounds']['response_bytes']['min']:.0f}–{c['training_bounds']['response_bytes']['max']:.0f}",f"{c['exceeds_training_max']['cpu_seconds']} / {c['exceeds_training_max']['rss_sampled_max_bytes']} / {c['exceeds_training_max']['response_bytes']}"] for c in r['cost_classes']['classes']])
add('## Future preflight, feature set and Auto readiness')
add()
add('Smallest useful candidate set: operation/output mode, Cell count, rays, effective per-Cell radius/profile/frequency, deterministic search policy/budget, bounded local bbox candidate and vertex/edge counts, sample/grid count, observed CPU capacity, and active interactive/async work. Geometry/count descriptors are correlated; retain a bounded count plus vertices provisionally, not every correlated density feature. Recommendation additionally needs candidate inventory/search-domain extent; Building Entry needs global scan context. Cells/search/grid variation are operationally required features but their coefficients are not identified by this fixed-default subset.')
add()
add('Recommended future preflight: **C, footprint + vertex/edge metadata**, as a bounded diagnostic prototype for the expensive ray/network operations; add an explicit query budget/fallback design before production use. Cheap bbox-only counts lose polygon complexity. Exact polygon intersections are unnecessary for conservative bbox metadata. For very cheap endpoints, preflight benefit is unknown and may justify skipping it. No new production query or index optimization is introduced here.')
add()
table(['Derivation','Readiness'],[[k,v] for k,v in r['readiness'].items()])
add('Future admission design likely needs resource profile + operation parameters + bounded local geometry + mixed-load state. No estimator is certified: only four independent held-out locations, one dataset/shared VM, fixed search policy, incomplete moderate-setting coverage, sample peaks and short async overlap. Eight-Cell demand could plausibly enter such a feature set, but this study measures six. The [separate capacity audit](./network-size-capacity-audit.md) measured six→eight Optimize at5.886→8.374s (2.6GHz) and5.745→8.249s (28GHz), with only one primary eight-Cell sample. Its repeat workflow consumes19 of20 attempts, leaving only one. Those limited compute observations and tight workflow budget do not justify a cap increase. Do not increase validation caps or infer capacity from linear Cell scaling.')
add()
add('Future bounded observability: operation, geometry count bucket, predicted/actual CPU and wall buckets, response-byte bucket, interactive/async active counts and underprediction flag. An internal cost-class field is useful only after a stable class exists. No raw coordinates, IP, project payload or credentials; this task adds no production telemetry.')
add()
add('## Validation and freeze')
add()
add('Baseline: backend full tests, race tests and vet; frontend423 tests, lint/build; existing real RF-budget and deadline browser E2Es passed on separate fresh servers. Final validation results are recorded in the JSON `validation` field after execution. Existing Vite large-chunk and Node environment warnings persist. New Python tests enforce held-out isolation/error arithmetic/repeat/domain/async/policy invariants; the disposable Go primitive test checks multipart/closed-ring accounting and conservative envelope nesting.')
add()
add(f"All ordinary measured RF responses succeeded: {r['summary']['all_rf_statuses_200']}; cross-repeat/profile canonical hashes stable: {r['summary']['scientific_response_hashes_stable_for_repeats_and_profiles']}. Six cancellation cases preserve charges and successful same-client follow-up; sampler/slots and async measurements remain test-only. No OOM event or kill; no claim of guaranteed memory safety follows.")
add()
add('Created files: `docs/auto-resource-geometry-calibration.md`, `.json` and `scripts/auto-resource-geometry/` tooling/tests. No VERSION/CHANGELOG bump: no externally visible behavior. Previous artifacts stay untouched. Freeze evidence and audit tooling, **not** a numeric estimator, margin, class or adaptive design.')
add()
add('**Single next action:** '+r['next_action'])
add()
add('[Full machine-readable evidence](./auto-resource-geometry-calibration.json) · [Reproduction harness](../scripts/auto-resource-geometry/README.md)')
pathlib.Path(a.output).write_text('\n'.join(lines)+'\n');print(a.output)
