#!/usr/bin/env python3
"""Publish measured envelopes and explicit non-certification without modifying evidence."""
import json,pathlib
from protocol import ROOT,HERE,load

def f(v):return 'unknown' if v is None else f'{v:.3f}'
def gib(v):return f'{v/(1<<30):.3f} GiB'
def describe(s):
 if not s.get('n'):return 'NOT TESTED'
 return f"{s['n']} groups; {s['http_failures']} HTTP failures; max request {s['max_request_seconds']:.3f}s; minimum headroom {s['minimum_deadline_headroom_seconds']:.3f}s; peak cgroup {gib(s['peak_cgroup_bytes'])}."
def report():
 p=ROOT/'docs/fixed-deployment-profile-certification.json';r=load(p)
 if not r.get('all_planned_complete'):raise ValueError('do not publish final verdicts for incomplete evidence')
 lock=load(HERE/'certification-lock.json')
 validation=load(HERE/'checks.json') if (HERE/'checks.json').exists() else {}
 if (HERE/'post-audit-checks.json').exists():validation=validation|load(HERE/'post-audit-checks.json')
 r['validation']=validation
 r['self_hosted_implication']='Docker/self-hosted installers may later show descriptive eligibility for the tested reference and exact pack. Native builds need separate runtime evidence; no packaging or resource selector added.'
 r['hosted_implication']='The operator controls deployment capacity and verifies the same workload/worker/concurrency envelope; no end-user hardware selector.'
 r['eight_cell_implication']='A separate preregistered eight-Cell operational and request-budget re-audit may be justified only if W1 reference profiles certify. Six remains the product cap; this study does not establish eight-Cell safety or solve the attempt budget.'
 r['development_sufficiency']='Fixed references are sufficient for the bounded current Ankara/W1 development envelope only; do not promise arbitrary datasets, W2 contention or API-valid maxima.' if r['certified_profile_ids'] else 'No complete fixed-reference certification yet; retain Auto-only development with explicit best-effort boundaries.'
 r['baseline_validation']={'backend_tests':'passed','backend_race':'passed','backend_vet':'passed','frontend_tests':'423 passed,68 files','lint':'passed','production_build':'passed','rf_budget_e2e':'passed in fresh isolated backend','rf_deadline_e2e':'passed in separate fresh isolated backend','resource_profile_and_cancel_experiment_tests':'passed','combined_e2e_initial_failure':'Two real tests ran concurrently from the same ClientIP, causing legitimate per-client denial. Corrected test invocation isolates their backend processes; production/tests not modified.'}
 p.write_text(json.dumps(r,indent=2)+'\n')
 ps=r['profiles'];minimum=r['minimum_certified_profile'];recommended=r['recommended_certified_profile']
 paragraphs=[f"# Conservative fixed deployment profile certification\n\nCertification date: **2026-10-05**, A.T.O.M **{r['source_version']}**, source `{r['baseline']['head']}` on `{r['baseline']['branch']}`. Starting Git status and diff were clean. Original command logs, including the excluded skipped/shared-client E2E invocations and successful isolated replacements, are retained in `scripts/fixed-deployment-profiles/baseline-evidence.json`.",
 f"Completed **{r['observed_groups']}/{r['planned_groups']}** locked groups. A: **{ps['A']['verdict']}**; B: **{ps['B']['verdict']}**; C: **{ps['C']['verdict']}**. Minimum certified reference: **{minimum or 'none'}**. Recommended certified reference: **{recommended or 'none'}**. These findings apply to the exact tested Ankara pack, RF inputs, runtime and production policy. They are not universal minimum hardware requirements.",
 "API-valid input and certified interactive workload are explicitly distinct. Selected W3 inputs remain valid and available as best effort, heavy or offline-style workloads. A W3 timeout at the unchanged 60-second safety boundary does not invalidate a passing W1 reference. Estimator-driven adaptive admission remains paused; Auto remains observation-only.",
 f"## Immutable evidence\n\nMain contract SHA256: `{r['lock_sha256']}`. Complete Optimize → explanation supplement SHA256: `{r['workflow_supplement_lock_sha256']}`. The supplement was frozen before its measurements and preserves the main gates, RF settings, domain/repeat assignment and original evidence. The original main explanation row measures explanation after an actual Optimize prerequisite; the supplement captures both calls inside the measured workflow.",
 "The stopped bootstrap contract and three completed preliminary rows are preserved under `scripts/fixed-deployment-profiles/invalid-bootstrap/` and excluded. The bootstrap incorrectly expected a Linux container marker from Auto and omitted the intended pre-RF verification call. A corrected successor was frozen before successor measurements. Numerical gates, workloads, repetition count and run seed were unchanged. Linux Auto environment remains unknown; independent known Docker image/HostConfig inspection establishes container provenance. Unknown observations never satisfy a requirement by themselves.",
 f"Valid Surface supplement SHA256: `{r['surface_supplement_lock_sha256']}`. Primary [machine-readable findings](./fixed-deployment-profile-certification.json), immutable [contract](../scripts/fixed-deployment-profiles/certification-lock.json), [workflow supplement](../scripts/fixed-deployment-profiles/workflow-supplement-lock.json), [domain manifest](../scripts/fixed-deployment-profiles/domain-manifest.json), [run plans](../scripts/fixed-deployment-profiles/run-plans.json), and [reproduction protocol](../scripts/fixed-deployment-profiles/README.md). Raw ledgers, logs, Auto/startup snapshots and async time series have SHA256-indexed deterministic gzip copies in `scripts/fixed-deployment-profiles/evidence/`. The [completion audit](../scripts/fixed-deployment-profiles/completion-audit.json) independently reconciles all 2,704 plan/fixture identities, verifies archived digests, preserves quality logs and covers every requested phase.",
 "## Dataset and resource scope\n\nThe exact `ankara-open-planning` **2026.07** pack has **161,784 indexed footprints**, **936,651 polygon vertices** and **451 inventory Cells**. It is planning-grade OpenStreetMap/OpenCellID-derived evidence with synthetic enrichment, not an operator inventory. No second legitimate real pack or safe generic dataset complexity ceiling was established."]
 for filename,digest in r['dataset']['sha256'].items():paragraphs.append(f"- `{filename}`: `{digest}`")
 paragraphs.append("\n| Reference | CPU quota | Hard memory | Role |\n|---|---:|---:|---|\n| A | 2 CPU | 4 GiB | minimum candidate |\n| B | 4 CPU | 8 GiB | recommended candidate |\n| C | 8 CPU | 10 GiB | higher bounded candidate |\n| D | unbounded | unbounded | development control, never certified |")
 paragraphs.append("Profiles are resource floors subject to all other assumptions, rather than exact machine identities. The tested candidate envelope includes the exact eight nearest-six inventory Cell layouts and default optimization priorities/constraints in the frozen fixtures. It does not cover arbitrary six-Cell combinations, custom per-cell RF profiles, an enabled radio-quality optimization objective, or every location in the pack. Other API-valid layouts/settings remain outside measured certification. C was measured at 8 CPU / 10 GiB; no 16 GiB extrapolation. No candidate is certified. The development VM has 10 CPUs and 12,600,156,160 bytes (~11.735 GiB) on an Apple M4 host with 24 GiB host RAM. The pinned image and Go toolchain are recorded in the contract/Auto snapshots. The measured backend binary uses Go 1.27.1 with CGO disabled; the observations are limited to this tested runtime and cannot qualify an unmeasured release-image binary or compiler version. The shipping Dockerfile and backend Go directive pin Go 1.26.6. That default shipping runtime has not been qualified here; it does not inherit the Go 1.27.1 reference verdict. CPU quota is a consumption ceiling, not dedicated physical-core reservation; shared host contention and CPU architecture/speed remain operational assumptions.")
 paragraphs.append("## Frozen workload classes\n\nW1 uses 120 rays, 400 m radius, 30 dBm, 120° beam, six Cells where applicable, both 2.6 and 28 GHz, normal interference bandwidths 20/100 MHz, and the unchanged legacy two-pass network search. It includes Simulate; Evaluate + six maps; Interference; Evaluate + maps → Interference → Re-evaluate + maps (15 protected attempts); Optimize + six optimized maps; Optimize + actual solution explanation; Optimize Azimuth; 25 m Coverage Surface; Building Entry; and a five-Cell Recommendation over the six-inventory-Cell enclosing polygon plus 20 m. Production/frontend payload builders generate all core fixtures.")
 paragraphs.append("W2 uses 240 rays and 600 m radius with the same six-Cell/frequency/power/beam assumptions. It includes Simulate, Evaluate + maps, Optimize + maps, Interference and 25 m Surface. Its bounded alternate Optimize search uses deterministic multi-start, 2 passes and 192 unique evaluations. This practical heavier envelope includes both legacy and that alternate; a failing alternate cannot be silently removed to make W2 certify.")
 paragraphs.append("W3 uses selected valid 360-ray / 1,500 m edge inputs, a separately preregistered 10 m Surface grid (90,601 cells) and bounded Pareto archive search with 3 passes / 768 unique evaluations, on sparse/dense domains and both frequencies. It probes Simulate, Optimize, Surface, Building Entry and Recommendation. The original 5 m / 1,500 m surface has 361,201 cells and is API-invalid under the unchanged 100,000-cell cap. The 5 m size also violates the unchanged 10 m minimum, and is rejected before the grid-count check. All 42 locked original requests remain validation negative controls. The frozen supplement annotation incorrectly expected HTTP 422; the production validator returns HTTP 400. That expectation mismatch is retained as a methodology violation, without altering the annotation or forcing qualification. The valid 10 m supplement was frozen before any W3 timing; it adds evidence without replacing controls or changing gates. W3 does not require interactive certification or promise API maxima such as 100,000 search evaluations, 720 rays / 5,000 m, huge polygons/surfaces or large experiment matrices.")
 paragraphs.append("## Frozen gates and measurement method\n\nBoth the original monotonic timer and UTC start/end intervals are retained. Where they disagree, the longer observed interval scores the unchanged 45 s elapsed gate; interrupted observations are retained and reported, with no replacement or timing exclusion. Every certified interactive response must be HTTP 200, complete its streamed read, and finish within **45 s**, retaining **15 s** (one quarter) of the existing 60 s deadline for variability, contention and transfer. A mere 59.9 s success cannot pass. Any failed repeat counts; there is no averaging away failures, favorable early stopping or post-measurement gate adjustment.")
 paragraphs.append("Kernel `memory.peak` must stay at or below **75% of the hard cgroup limit**, with no `oom`, `oom_kill` or `max` events. At least **25%** hard-memory headroom is retained for the loaded dataset, runtime, async retained state, buffers and cgroup page cache. `memory.current`, kernel lifetime peak, process RSS and Go heap are recorded; sampled RSS is never a memory reservation. The primary memory gate includes startup and retained W2 state in W1/W2/mixed batches. W3 process histories are separate and reported. Missing required memory/CPU files fail the batch.")
 paragraphs.append("CPU usage, quota periods, throttled periods and throttle duration are observed. Quota saturation/throttling alone is allowed; observable HTTP completion and headroom determine certification. Mixed process CPU includes both interactive/background computation and instrumentation and is not attributed as individual request pricing.")
 paragraphs.append("Requests use a real Linux TCP loopback listener, production Gin routes/body/attempt/concurrency/deadline middleware, real serialization and streamed `io.Copy`/SHA256 reads. Distinct loopback source IPs create distinct production ClientIP buckets; forwarded proxy headers are disabled. Primary performance runs stream large response bodies. The separate science-only Building Entry supplement retains JSON for canonical comparison; its latency/memory are excluded from performance scoring. Optimize/job responses are retained only for actual follow-ups. Entity bytes are uncompressed and exclude HTTP framing; no network SLO is invented.")
 paragraphs.append("Three Latin-order profile segments balance profile order, with pre-generated seeded shuffles across geometry/frequency/operation. Main services are warmed by one unmeasured valid Simulate, with no forced GC or OS-cache eviction. A fresh process starts each segment; within-segment state is long-running. Fresh-process first Optimize on sparse/dense at 2.6 GHz has three repeats per profile, with startup/index time separately recorded. The 120-workflow explanation supplement uses separately warmed services. GOMAXPROCS, GOGC and GOMEMLIMIT remain Go defaults.")
 paragraphs.append("Five W1 repeats per critical operation/profile/band/frequency alternate two domains (3 and 2 observations). W2 has three, W3 three where planned, and each mixed scenario/domain/frequency/profile has three. Mixed-load launch is blocked until five matching isolated Evaluate/Optimize references exist for that exact profile, domain, RF and search fixture. The completeness guard and keys were frozen before the valid measurements.")
 paragraphs.append("## Geometry domains\n\nDeterministic inventory anchors select the nearest six distinct Cells, rank 400 m enclosing-box vertex density, and target sparse/medium/dense/very-dense quantile strata. Two disjoint 802 m enclosing envelopes per band exclude every earlier fitting domain. Excluding all earlier validation areas as well exhausted the inventory during geometry-only selection; reuse of validation areas was permitted before freeze. Band labels are selection strata, not universal density thresholds. Enlarged W3 envelopes may overlap.")
 paragraphs.append("| Domain | Footprints in 400 m enclosing domain | Vertices/km² | Selection rank |\n|---|---:|---:|---:|")
 for d in r['domains']:paragraphs.append(f"| {d['id']} | {d['stats']['footprints']} | {d['stats']['vertices_per_km2']:.1f} | {d['rank']} |")
 paragraphs.append("## Certified envelope matrix\n\n| Envelope | A | B | C |\n|---|---|---|---|")
 for key in r['matrix']['A']:paragraphs.append('| '+key+' | '+' | '.join(r['matrix'][p][key] for p in ['A','B','C'])+' |')
 paragraphs.append("## Profile comparison\n\n| Profile | W1 max seconds | Concurrency max seconds | Async max seconds | Operational memory headroom | W2 certified |\n|---|---:|---:|---:|---:|---|")
 for profile,x in r['profile_comparison'].items():paragraphs.append(f"| {profile} | {f(x['W1_max_seconds'])} | {f(x['concurrency_max_seconds'])} | {f(x['async_max_seconds'])} | {f(x['memory_headroom_fraction']*100 if x['memory_headroom_fraction'] is not None else None)}% | {x['W2_certified']} |")
 paragraphs.append(r['recommendation_method']+f" Minimum reference: **{minimum or 'none'}**; recommended larger reference: **{recommended or 'none'}**. The JSON records each eligible comparison. C's W2 result does not imply interactive support for W3 maxima.")
 for profile in ['A','B','C','D']:
  x=ps[profile];paragraphs.append(f"\n## Profile {profile}: {x['verdict']}\n\nW1 single: {describe(x['single_W1'])}\n\nW2 single: {describe(x['single_W2'])}\n\nW3 valid probes: {describe(x['W3'])}\n\nW3 validation negative controls: {describe(x['W3_validation_negative_controls'])}")
  paragraphs.append("| Scenario | Groups | HTTP failures | Max request seconds | Minimum deadline headroom seconds |\n|---|---:|---:|---:|---:|")
  for category in ['concurrency','normal_async','sustained_async']:
   for op,s in x[category].items():
    paragraphs.append(f"| {op} | {s.get('n',0)} | {s.get('http_failures','—')} | {f(s.get('max_request_seconds'))} | {f(s.get('minimum_deadline_headroom_seconds'))} |")
  paragraphs.append(f"\nPrimary operational memory headroom: {f(x['memory_headroom_min_fraction']*100 if x['memory_headroom_min_fraction'] is not None else None)}%. Cancellation/release: {'PASS' if x['cancellation_pass'] else 'NOT TESTED/FAIL'} ({x['cancellation_cases']} cases). Across all measured classes, peak RSS {gib(x['memory'].get('peak_rss_bytes',0))}, peak cgroup {gib(x['memory'].get('peak_cgroup_bytes',0))}. Throttle duration {x['memory'].get('throttle_seconds',0):.3f}s across {x['memory'].get('throttled_periods',0)} throttled periods.")
  observed=x['observed_gates']
  paragraphs.append(f"Observed gates (separate from formal certification): W1 single numerical {'PASS' if observed['W1_single_numerical'] else 'FAIL'}; concurrency numerical/overlap {'PASS' if observed['concurrency_numerical_and_overlap'] else 'FAIL'}; normal async numerical/overlap {'PASS' if observed['normal_async_numerical_and_overlap'] else 'FAIL'}; sustained async numerical/overlap {'PASS' if observed['sustained_async_numerical_and_overlap'] else 'FAIL'}; fresh first-request numerical {'PASS' if observed['fresh_first_request_numerical'] else 'NOT TESTED/FAIL'}. Fresh: {describe(x['fresh_first_request'])} Formal qualification also requires complete evidence, scientific invariance and no methodology violation; the retained negative-control status mismatch prevents every candidate's formal qualification.")
  if x['largest_latency_inflation']:
   z=x['largest_latency_inflation'];paragraphs.append(f"Largest matching-reference latency inflation: **{z['ratio']:.3f}×**, {z['scenario']} / {z['endpoint']} on {z['domain']} at {z['frequency_ghz']} GHz ({z['mixed_wall_seconds']:.3f}s vs isolated median {z['isolated_median_seconds']:.3f}s).")
  counts={}
  for case in x['gate_failures']:counts[case['class']]=counts.get(case['class'],0)+1
  paragraphs.append(f"Non-cancellation numerical gate failures by class: `{json.dumps(counts,sort_keys=True)}`. Full failure cases and async/cancellation evidence remain in JSON/evidence; W3 failures are retained rather than reassigned to W1/W2.")
 paragraphs.append(f"Surface negative controls: locked expected HTTP **422**; observed statuses `{json.dumps(r['validation_negative_controls']['observed_status_counts'],sort_keys=True)}`. Source validation rejects 5 m because cell size must be 10–250 m and the route emits HTTP 400. Recorded response-body SHA256 agrees with the source error JSON: **{r['validation_negative_controls']['source_error_bodies_match']}**. The incorrect preregistered status assumption remains failed; it is not converted into a passing control.")
 if r['methodology_violations']:paragraphs.append("Methodology violations prevent formal certification: "+'; '.join(r['methodology_violations']))
 paragraphs.append("## Operational findings\n\nConcurrency uses two distinct clients for Optimize + Optimize, Optimize + Evaluate and Evaluate + Evaluate, on sparse/dense and both frequencies. Both replies must succeed and no global/per-client slot may leak. A profile lacking this guarantee is not generally supported under the unchanged global concurrency 2.")
 sustain=r['sustained'];paragraphs.append(f"Normal async overlap keeps worker **1** and queue **16**, with uncached 16-run jobs. Sustained overlap refills four active/queued uncached 64-run jobs for approximately 30 seconds, bounded by 64 submissions, and then cancels/drains. Every interactive request must have temporal overlap with actual computation. Sustained evidence requires at least 95% active-worker samples during the first 30 seconds. Sustained cases passing this behavioral gate: **{sum(s['pass'] for s in sustain)}/{len(sustain)}**. Submission/queue depth alone is insufficient; per-case fractions/durations are published.")
 failedAsync=[case for case in r['async_verification'] if not case['pass']]
 if failedAsync:
  paragraphs.append("Some async observations lack the locked per-request overlap evidence. This prevents general W1 certification for the affected profile even when its HTTP latency and memory pass. The bounded 64-submission source can exhaust before 30 seconds on faster configurations. A final call after the 30-second refill window may also find the background queue drained; this is an evidence/protocol failure, not proof that hardware compute capacity is insufficient. Failed cases remain included, with no replacement or exclusion.")
  for case in failedAsync:paragraphs.append(f"- {case['batch']} / index {case['plan_index']}: "+'; '.join(case['failure_reasons']))
 paragraphs.append("Cancellation sends a real client cancellation 100 ms into expensive Optimize, awaits handler completion, requires release within 2 seconds, then verifies same-client and other-client Evaluate success, zero global/per-client activity, and two charged same-client attempts (canceled Optimize + subsequent Evaluate). Attempt charging, the anchored 20/60 s window and ClientIP identity remain unchanged.")
 paragraphs.append("Evaluate + maps costs **7 attempts**; Optimize + maps **7**; Optimize + explanation **2**; Evaluate + maps → Interference → Re-evaluate + maps **15**. Two consecutive map workflows cost 14. A third rapid Evaluate/map workflow reaches the existing 20-attempt boundary and its 21st protected attempt is denied. Separate real budget E2E verifies successful output/repeated scientific hashes, preserved UI inspection without RF requests, and unchanged abuse behavior. This does not solve an eight-Cell budget issue.")
 paragraphs.append(f"Building Entry scientific supplement SHA256: `{r['science_supplement_lock_sha256']}`. The main contract incorrectly assumed RF responses had no runtime fields; auditing identified `diagnostics.elapsed_ms`. This explicit correction preserves scientific values and all headroom gates. Its 156 requests repeat all original ABC W1/W3 Building Entry cases. Complete response canonicalization excludes only `diagnostics.elapsed_ms`; raw hashes remain in the evidence. Canonicalizer regression checks preserve numeric precision, array order, scientific values and all other diagnostics. Supplemental memory/latency does not score deployment headroom.")
 scientific=r['scientific_invariance'];paragraphs.append(f"Scientific response invariance: **{'PASS' if scientific['stable'] else 'FAIL'}**, {scientific['request_groups']} exact request/endpoint groups, {scientific['groups_compared_across_profiles']} compared across resource profiles. Deterministic scientific response hashes include existing fingerprints; Auto diagnostic/runtime logs are excluded. No equations, search traversal, Pareto semantics or fingerprints were changed.")
 if r['clock_discontinuities']:
  paragraphs.append("Recorded clock discontinuities are consistent with VM pause or clock interruption, with cause not independently verified. After discovering them, a host `caffeinate -i` assertion prevents idle sleep until the finisher exits; its start timestamp is recorded in JSON. User-forced suspension remains possible. This observer-side intervention does not change RF settings, quotas, repeats or gates. They are not evidence of intrinsic RF compute cost. Failed/interrupted observations remain in their original workload/profile, and the longer elapsed interval cannot pass the unchanged headroom gate.")
  for event in r['clock_discontinuities']:paragraphs.append(f"- {event['batch']} / {event['level']} / {event['operation']}: HTTP {event['status']}; monotonic {event['monotonic_request_seconds']:.3f}s; timestamp interval {event['timestamp_interval_seconds']:.3f}s; process CPU {event['cpu_seconds']:.3f}s.")
 largest=r['largest_single_response'];workflow=r['largest_workflow'];overall=r['overall_observation']
 paragraphs.append(f"Largest single response: **{largest['response_bytes']:,} bytes** ({largest['operation']}, {largest['class_id']}, {largest['profile']}, {largest['domain']}). Largest measured W1/W2 logical workflow: **{workflow['response_bytes']:,} bytes** ({workflow['operation']}, {workflow['level']}, {workflow['profile_id']}, {workflow['domain']}). Its entity-byte transfer alone would take ~{workflow['response_bytes']*8/10_000_000:.2f}s at an illustrative 10 Mbps or ~{workflow['response_bytes']*8/100_000_000:.2f}s at 100 Mbps, before protocol overhead. Larger transfers can dominate interactive experience on slower links; this arithmetic is not a network SLO.")
 paragraphs.append(f"Across all measured classes: peak observed RSS **{gib(overall['peak_rss_bytes'])}**, peak kernel cgroup memory **{gib(overall['peak_cgroup_bytes'])}**, OOM events **{overall['max_oom_events']}**, OOM kills **{overall['max_oom_kill_events']}**. Minimum headroom including W3/unqualified inputs is {overall['minimum_deadline_headroom_seconds']:.3f}s; W1/W2 headroom is reported separately per profile; qualification requires at least 15 s, and none of the candidates qualifies.")
 paragraphs.append("## Decisions and product boundary\n\n"+r['development_sufficiency']+' '+r['self_hosted_implication']+' '+r['hosted_implication'])
 paragraphs.append("Future Auto may describe resource-floor eligibility only with known effective CPU, known hard memory ceiling, verified runtime/container assumptions, exact dataset identity/hashes/counts, worker/queue settings and fixed concurrency policy. Transient free RAM is not profile identity. Linux environment unknown requires independent known container evidence. The tested Go toolchain/binary and supported Cell layout/workload assumptions must also be verified; unknown or untested facts keep descriptive eligibility unverified. Resource floors alone never imply certification. No matcher, CPU/RAM selector, profile selector, performance preset or workload rejection is installed.")
 paragraphs.append("The reusable production Auto dataset representation already distinguishes unavailable metadata (nil/null) from real zero counts. The frozen historical preflight prototype's nil-safe index query can return zero for unavailable geometry. Historical evidence is preserved. The corrected audit-only successor `fixedGeometryObservation` returns unknown/null for nil and known zero for an empty index, with malformed/null/empty regression tests. No production diagnostic surface changed.")
 paragraphs.append(r['eight_cell_implication']+" Estimator fitting, coefficients, margins and admission design remain paused. No eight-Cell product configuration was tested or enabled here.")
 paragraphs.append("## Validation and freeze\n\nBackend tests/race/vet, frontend tests/lint/build, separately isolated RF budget/deadline E2E, Auto resource-profile tests, certification/lock/mixed-reference/resource-floor/cancellation/async gate tests, docs build/validation, version consistency and whitespace checks are recorded in JSON. The initial combined E2E collision is retained as a test-invocation issue; independently fresh backends passed without production changes.")
 if validation:
  paragraphs.append("| Check | Result |\n|---|---|")
  for name,v in validation.items():paragraphs.append(f"| {name} | {'PASS' if v['exit_code']==0 else 'FAIL'} |")
 paragraphs.append(r['version_recommendation']+' '+r['freeze_decision']+" **Single next action:** "+r['next_action'])
 paragraphs.append("## Limitations\n\n"+'\n'.join('- '+v for v in r['limitations']))
 output=''
 for paragraph in paragraphs:
  separator='\n' if output and output.rstrip().split('\n')[-1].startswith('|') and paragraph.startswith('|') else '\n\n'
  output+=separator+paragraph if output else paragraph
 (ROOT/'docs/fixed-deployment-profile-certification.md').write_text(output+'\n')
 # Only passing references may be added to deployment documentation.
 deployment=ROOT/'docs/deployment.md';s=deployment.read_text();marker='## Certified Ankara reference deployments'
 if minimum and marker not in s:
  block=f"## Certified Ankara reference deployments\n\nCertification dated **2026-10-05**, A.T.O.M **{r['source_version']}**, names Profile **{minimum}** as the minimum certified reference"
  if recommended:block+=f" and Profile **{recommended}** as the recommended certified reference"
  block+=' for the exact Ankara 2026.07 dataset and frozen six-Cell interactive envelope. These are reference deployments, not universal hardware requirements. '
  block+='; '.join(f"{p}: {lock['profiles'][p]['cpus']} CPU / {lock['profiles'][p]['memory_gib']} GiB ({ps[p]['verdict']})" for p in r['certified_profile_ids'])+'.\n\n'
  block+='The default Dockerfile currently pins Go 1.26.6 and has not been qualified by these measurements. Certification requires the tested Linux arm64/cgroup v2 / Go 1.27.1 runtime (CGO disabled), default Go scheduler/GC behavior, fixed RF policy (20 attempts / anchored 60 s / ClientIP, 2 global slots, 1 per-client slot, 60 s deadline, six Cells), experiment worker 1 / queue 16, and the exact pack hashes. W1 uses 120 rays / 400 m / both planning frequencies. W2 and valid heavier workloads have distinct certification boundaries; unbounded development, arbitrary datasets, untested W2 contention and API maxima are not covered. See the [complete profile matrix and evidence](./fixed-deployment-profile-certification.md). Auto remains observation-only, and no user resource settings or admission changes are added.\n\n'
  s=s.replace('## Configuration',block+'## Configuration',1)
  s=s.replace('This foundation establishes no automatic scaling or certified minimum\nor recommended hardware.', 'This foundation itself establishes no automatic scaling or hardware guarantee;\ncertified references require the separate exact-dataset workload study below.')
  deployment.write_text(s)
 print('Report written; minimum',minimum,'recommended',recommended)
if __name__=='__main__':report()
